//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/util/Attribute.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneUtilAttribute")
#ifdef RESTRICT_OrgApacheLuceneUtilAttribute
#define INCLUDE_ALL_OrgApacheLuceneUtilAttribute 0
#else
#define INCLUDE_ALL_OrgApacheLuceneUtilAttribute 1
#endif
#undef RESTRICT_OrgApacheLuceneUtilAttribute

#if !defined (OrgApacheLuceneUtilAttribute_) && (INCLUDE_ALL_OrgApacheLuceneUtilAttribute || defined(INCLUDE_OrgApacheLuceneUtilAttribute))
#define OrgApacheLuceneUtilAttribute_

@protocol OrgApacheLuceneUtilAttribute < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneUtilAttribute)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneUtilAttribute)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneUtilAttribute")
