//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/util/MemoryModel.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneUtilMemoryModel")
#ifdef RESTRICT_OrgApacheLuceneUtilMemoryModel
#define INCLUDE_ALL_OrgApacheLuceneUtilMemoryModel 0
#else
#define INCLUDE_ALL_OrgApacheLuceneUtilMemoryModel 1
#endif
#undef RESTRICT_OrgApacheLuceneUtilMemoryModel

#if !defined (OrgApacheLuceneUtilMemoryModel_) && (INCLUDE_ALL_OrgApacheLuceneUtilMemoryModel || defined(INCLUDE_OrgApacheLuceneUtilMemoryModel))
#define OrgApacheLuceneUtilMemoryModel_

@class IOSClass;

@interface OrgApacheLuceneUtilMemoryModel : NSObject

#pragma mark Public

- (instancetype)init;

- (jint)getArraySize;

- (jint)getClassSize;

- (jint)getPrimitiveSizeWithIOSClass:(IOSClass *)clazz;

- (jint)getReferenceSize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneUtilMemoryModel)

FOUNDATION_EXPORT void OrgApacheLuceneUtilMemoryModel_init(OrgApacheLuceneUtilMemoryModel *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneUtilMemoryModel)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneUtilMemoryModel")
