//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/util/SorterTemplate.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneUtilSorterTemplate")
#ifdef RESTRICT_OrgApacheLuceneUtilSorterTemplate
#define INCLUDE_ALL_OrgApacheLuceneUtilSorterTemplate 0
#else
#define INCLUDE_ALL_OrgApacheLuceneUtilSorterTemplate 1
#endif
#undef RESTRICT_OrgApacheLuceneUtilSorterTemplate

#if !defined (OrgApacheLuceneUtilSorterTemplate_) && (INCLUDE_ALL_OrgApacheLuceneUtilSorterTemplate || defined(INCLUDE_OrgApacheLuceneUtilSorterTemplate))
#define OrgApacheLuceneUtilSorterTemplate_

@interface OrgApacheLuceneUtilSorterTemplate : NSObject

#pragma mark Public

- (instancetype)init;

- (void)insertionSortWithInt:(jint)lo
                     withInt:(jint)hi;

- (void)mergeSortWithInt:(jint)lo
                 withInt:(jint)hi;

- (void)quickSortWithInt:(jint)lo
                 withInt:(jint)hi;

#pragma mark Protected

- (jint)compareWithInt:(jint)i
               withInt:(jint)j;

- (jint)comparePivotWithInt:(jint)j;

- (void)setPivotWithInt:(jint)i;

- (void)swapWithInt:(jint)i
            withInt:(jint)j;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneUtilSorterTemplate)

FOUNDATION_EXPORT void OrgApacheLuceneUtilSorterTemplate_init(OrgApacheLuceneUtilSorterTemplate *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneUtilSorterTemplate)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneUtilSorterTemplate")
