//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/search/spans/SpanTermQuery.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchSpansSpanTermQuery")
#ifdef RESTRICT_OrgApacheLuceneSearchSpansSpanTermQuery
#define INCLUDE_ALL_OrgApacheLuceneSearchSpansSpanTermQuery 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchSpansSpanTermQuery 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchSpansSpanTermQuery

#if !defined (OrgApacheLuceneSearchSpansSpanTermQuery_) && (INCLUDE_ALL_OrgApacheLuceneSearchSpansSpanTermQuery || defined(INCLUDE_OrgApacheLuceneSearchSpansSpanTermQuery))
#define OrgApacheLuceneSearchSpansSpanTermQuery_

#define RESTRICT_OrgApacheLuceneSearchSpansSpanQuery 1
#define INCLUDE_OrgApacheLuceneSearchSpansSpanQuery 1
#include "org/apache/lucene/search/spans/SpanQuery.h"

@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneIndexTerm;
@class OrgApacheLuceneSearchSpansSpans;
@protocol JavaUtilSet;

@interface OrgApacheLuceneSearchSpansSpanTermQuery : OrgApacheLuceneSearchSpansSpanQuery {
 @public
  OrgApacheLuceneIndexTerm *term_;
}

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term;

- (jboolean)isEqual:(id)obj;

- (void)extractTermsWithJavaUtilSet:(id<JavaUtilSet>)terms;

- (NSString *)getField;

- (OrgApacheLuceneSearchSpansSpans *)getSpansWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

- (OrgApacheLuceneIndexTerm *)getTerm;

- (NSUInteger)hash;

- (NSString *)toStringWithNSString:(NSString *)field;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchSpansSpanTermQuery)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchSpansSpanTermQuery, term_, OrgApacheLuceneIndexTerm *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchSpansSpanTermQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneSearchSpansSpanTermQuery *self, OrgApacheLuceneIndexTerm *term);

FOUNDATION_EXPORT OrgApacheLuceneSearchSpansSpanTermQuery *new_OrgApacheLuceneSearchSpansSpanTermQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneIndexTerm *term) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchSpansSpanTermQuery *create_OrgApacheLuceneSearchSpansSpanTermQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneIndexTerm *term);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchSpansSpanTermQuery)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchSpansSpanTermQuery")
