//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/index/CoalescedDeletes.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Integer.h"
#include "java/lang/Iterable.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"
#include "java/util/Iterator.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/Set.h"
#include "java/util/Spliterator.h"
#include "java/util/function/Consumer.h"
#include "org/apache/lucene/index/BufferedDeletes.h"
#include "org/apache/lucene/index/BufferedDeletesStream.h"
#include "org/apache/lucene/index/CoalescedDeletes.h"
#include "org/apache/lucene/index/FrozenBufferedDeletes.h"
#include "org/apache/lucene/index/Term.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/util/PriorityQueue.h"

@class OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue;

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface OrgApacheLuceneIndexCoalescedDeletes_1 : NSObject < JavaLangIterable > {
 @public
  OrgApacheLuceneIndexCoalescedDeletes *this$0_;
}

- (instancetype)initWithOrgApacheLuceneIndexCoalescedDeletes:(OrgApacheLuceneIndexCoalescedDeletes *)outer$;

- (id<JavaUtilIterator>)iterator;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexCoalescedDeletes_1)

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes_1 *self, OrgApacheLuceneIndexCoalescedDeletes *outer$);

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_1 *new_OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_1 *create_OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$);

@interface OrgApacheLuceneIndexCoalescedDeletes_2 : NSObject < JavaLangIterable > {
 @public
  OrgApacheLuceneIndexCoalescedDeletes *this$0_;
}

- (instancetype)initWithOrgApacheLuceneIndexCoalescedDeletes:(OrgApacheLuceneIndexCoalescedDeletes *)outer$;

- (id<JavaUtilIterator>)iterator;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexCoalescedDeletes_2)

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes_2 *self, OrgApacheLuceneIndexCoalescedDeletes *outer$);

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_2 *new_OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_2 *create_OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$);

@interface OrgApacheLuceneIndexCoalescedDeletes_2_1 : NSObject < JavaUtilIterator > {
 @public
  id<JavaUtilIterator> iter_;
}

- (instancetype)initWithOrgApacheLuceneIndexCoalescedDeletes_2:(OrgApacheLuceneIndexCoalescedDeletes_2 *)outer$;

- (jboolean)hasNext;

- (OrgApacheLuceneIndexBufferedDeletesStream_QueryAndLimit *)next;

- (void)remove;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexCoalescedDeletes_2_1)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCoalescedDeletes_2_1, iter_, id<JavaUtilIterator>)

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(OrgApacheLuceneIndexCoalescedDeletes_2_1 *self, OrgApacheLuceneIndexCoalescedDeletes_2 *outer$);

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_2_1 *new_OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(OrgApacheLuceneIndexCoalescedDeletes_2 *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_2_1 *create_OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(OrgApacheLuceneIndexCoalescedDeletes_2 *outer$);

@interface OrgApacheLuceneIndexCoalescedDeletes_3 : NSObject < JavaUtilIterator > {
 @public
  OrgApacheLuceneIndexTerm *current_;
  OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *queue_;
  IOSObjectArray *top_;
  jint numTop_;
}

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)capture$0;

- (jboolean)hasNext;

- (OrgApacheLuceneIndexTerm *)next;

- (void)remove;

- (void)pullTop;

- (void)pushTop;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexCoalescedDeletes_3)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCoalescedDeletes_3, current_, OrgApacheLuceneIndexTerm *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCoalescedDeletes_3, queue_, OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCoalescedDeletes_3, top_, IOSObjectArray *)

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(OrgApacheLuceneIndexCoalescedDeletes_3 *self, id<JavaUtilList> capture$0);

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_3 *new_OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(id<JavaUtilList> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_3 *create_OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(id<JavaUtilList> capture$0);

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_3_pullTop(OrgApacheLuceneIndexCoalescedDeletes_3 *self);

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_3_pushTop(OrgApacheLuceneIndexCoalescedDeletes_3 *self);

@interface OrgApacheLuceneIndexCoalescedDeletes_SubIterator : NSObject {
 @public
  id<JavaUtilIterator> iterator_;
  OrgApacheLuceneIndexTerm *current_;
  jint index_;
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexCoalescedDeletes_SubIterator)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCoalescedDeletes_SubIterator, iterator_, id<JavaUtilIterator>)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCoalescedDeletes_SubIterator, current_, OrgApacheLuceneIndexTerm *)

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *self);

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_SubIterator *new_OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_SubIterator *create_OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexCoalescedDeletes_SubIterator)

@interface OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue : OrgApacheLuceneUtilPriorityQueue

- (instancetype)initWithInt:(jint)size;

- (jboolean)lessThanWithId:(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)a
                    withId:(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)b;

- (OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)pop;

- (OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)top;

- (OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)insertWithOverflowWithId:(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)arg0;

- (OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)addWithId:(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)arg0;

- (OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)getSentinelObject;

- (OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)updateTop;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue)

__attribute__((unused)) static void OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_(OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *self, jint size);

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *new_OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_(jint size) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *create_OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_(jint size);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue)

@implementation OrgApacheLuceneIndexCoalescedDeletes

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneIndexCoalescedDeletes_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)description {
  return JreStrcat("$I$IC", @"CoalescedDeletes(termSets=", [((id<JavaUtilList>) nil_chk(iterables_)) size], @",queries=", [((id<JavaUtilMap>) nil_chk(queries_)) size], ')');
}

- (void)updateWithOrgApacheLuceneIndexFrozenBufferedDeletes:(OrgApacheLuceneIndexFrozenBufferedDeletes *)inArg {
  [((id<JavaUtilList>) nil_chk(iterables_)) addWithId:[((OrgApacheLuceneIndexFrozenBufferedDeletes *) nil_chk(inArg)) termsIterable]];
  for (jint queryIdx = 0; queryIdx < ((IOSObjectArray *) nil_chk(inArg->queries_))->size_; queryIdx++) {
    OrgApacheLuceneSearchQuery *query = IOSObjectArray_Get(inArg->queries_, queryIdx);
    [((id<JavaUtilMap>) nil_chk(queries_)) putWithId:query withId:JreLoadStatic(OrgApacheLuceneIndexBufferedDeletes, MAX_INT)];
  }
}

- (id<JavaLangIterable>)termsIterable {
  return create_OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(self);
}

- (id<JavaLangIterable>)queriesIterable {
  return create_OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(self);
}

+ (id<JavaUtilIterator>)mergedIteratorWithJavaUtilList:(id<JavaUtilList>)iterators {
  return OrgApacheLuceneIndexCoalescedDeletes_mergedIteratorWithJavaUtilList_(iterators);
}

- (void)dealloc {
  RELEASE_(queries_);
  RELEASE_(iterables_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 0, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 1, 2, -1, -1, -1, -1 },
    { NULL, "LJavaLangIterable;", 0x1, -1, -1, -1, 3, -1, -1 },
    { NULL, "LJavaLangIterable;", 0x1, -1, -1, -1, 4, -1, -1 },
    { NULL, "LJavaUtilIterator;", 0x8, 5, 6, -1, 7, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(description);
  methods[2].selector = @selector(updateWithOrgApacheLuceneIndexFrozenBufferedDeletes:);
  methods[3].selector = @selector(termsIterable);
  methods[4].selector = @selector(queriesIterable);
  methods[5].selector = @selector(mergedIteratorWithJavaUtilList:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "queries_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x10, -1, -1, 8, -1 },
    { "iterables_", "LJavaUtilList;", .constantValue.asLong = 0, 0x10, -1, -1, 9, -1 },
  };
  static const void *ptrTable[] = { "toString", "update", "LOrgApacheLuceneIndexFrozenBufferedDeletes;", "()Ljava/lang/Iterable<Lorg/apache/lucene/index/Term;>;", "()Ljava/lang/Iterable<Lorg/apache/lucene/index/BufferedDeletesStream$QueryAndLimit;>;", "mergedIterator", "LJavaUtilList;", "(Ljava/util/List<Ljava/util/Iterator<Lorg/apache/lucene/index/Term;>;>;)Ljava/util/Iterator<Lorg/apache/lucene/index/Term;>;", "Ljava/util/Map<Lorg/apache/lucene/search/Query;Ljava/lang/Integer;>;", "Ljava/util/List<Ljava/lang/Iterable<Lorg/apache/lucene/index/Term;>;>;", "LOrgApacheLuceneIndexCoalescedDeletes_SubIterator;LOrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCoalescedDeletes = { "CoalescedDeletes", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x0, 6, 2, -1, 10, -1, -1, -1 };
  return &_OrgApacheLuceneIndexCoalescedDeletes;
}

@end

void OrgApacheLuceneIndexCoalescedDeletes_init(OrgApacheLuceneIndexCoalescedDeletes *self) {
  NSObject_init(self);
  JreStrongAssignAndConsume(&self->queries_, new_JavaUtilHashMap_init());
  JreStrongAssignAndConsume(&self->iterables_, new_JavaUtilArrayList_init());
}

OrgApacheLuceneIndexCoalescedDeletes *new_OrgApacheLuceneIndexCoalescedDeletes_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCoalescedDeletes, init)
}

OrgApacheLuceneIndexCoalescedDeletes *create_OrgApacheLuceneIndexCoalescedDeletes_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCoalescedDeletes, init)
}

id<JavaUtilIterator> OrgApacheLuceneIndexCoalescedDeletes_mergedIteratorWithJavaUtilList_(id<JavaUtilList> iterators) {
  OrgApacheLuceneIndexCoalescedDeletes_initialize();
  return create_OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(iterators);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneIndexCoalescedDeletes)

@implementation OrgApacheLuceneIndexCoalescedDeletes_1

- (instancetype)initWithOrgApacheLuceneIndexCoalescedDeletes:(OrgApacheLuceneIndexCoalescedDeletes *)outer$ {
  OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(self, outer$);
  return self;
}

- (id<JavaUtilIterator>)iterator {
  JavaUtilArrayList *subs = create_JavaUtilArrayList_initWithInt_([((id<JavaUtilList>) nil_chk(this$0_->iterables_)) size]);
  for (id<JavaLangIterable> __strong iterable in this$0_->iterables_) {
    [subs addWithId:[((id<JavaLangIterable>) nil_chk(iterable)) iterator]];
  }
  return OrgApacheLuceneIndexCoalescedDeletes_mergedIteratorWithJavaUtilList_(subs);
}

- (void)forEachWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)arg0 {
  JavaLangIterable_forEachWithJavaUtilFunctionConsumer_(self, arg0);
}

- (id<JavaUtilSpliterator>)spliterator {
  return JavaLangIterable_spliterator(self);
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilIterator;", 0x1, -1, -1, -1, 0, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneIndexCoalescedDeletes:);
  methods[1].selector = @selector(iterator);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LOrgApacheLuceneIndexCoalescedDeletes;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Iterator<Lorg/apache/lucene/index/Term;>;", "LOrgApacheLuceneIndexCoalescedDeletes;", "termsIterable", "Ljava/lang/Object;Ljava/lang/Iterable<Lorg/apache/lucene/index/Term;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCoalescedDeletes_1 = { "", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x8018, 2, 1, 1, -1, 2, 3, -1 };
  return &_OrgApacheLuceneIndexCoalescedDeletes_1;
}

@end

void OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes_1 *self, OrgApacheLuceneIndexCoalescedDeletes *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
}

OrgApacheLuceneIndexCoalescedDeletes_1 *new_OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCoalescedDeletes_1, initWithOrgApacheLuceneIndexCoalescedDeletes_, outer$)
}

OrgApacheLuceneIndexCoalescedDeletes_1 *create_OrgApacheLuceneIndexCoalescedDeletes_1_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCoalescedDeletes_1, initWithOrgApacheLuceneIndexCoalescedDeletes_, outer$)
}

@implementation OrgApacheLuceneIndexCoalescedDeletes_2

- (instancetype)initWithOrgApacheLuceneIndexCoalescedDeletes:(OrgApacheLuceneIndexCoalescedDeletes *)outer$ {
  OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(self, outer$);
  return self;
}

- (id<JavaUtilIterator>)iterator {
  return create_OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(self);
}

- (void)forEachWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)arg0 {
  JavaLangIterable_forEachWithJavaUtilFunctionConsumer_(self, arg0);
}

- (id<JavaUtilSpliterator>)spliterator {
  return JavaLangIterable_spliterator(self);
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilIterator;", 0x1, -1, -1, -1, 0, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneIndexCoalescedDeletes:);
  methods[1].selector = @selector(iterator);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LOrgApacheLuceneIndexCoalescedDeletes;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Iterator<Lorg/apache/lucene/index/BufferedDeletesStream$QueryAndLimit;>;", "LOrgApacheLuceneIndexCoalescedDeletes;", "queriesIterable", "Ljava/lang/Object;Ljava/lang/Iterable<Lorg/apache/lucene/index/BufferedDeletesStream$QueryAndLimit;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCoalescedDeletes_2 = { "", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x8018, 2, 1, 1, -1, 2, 3, -1 };
  return &_OrgApacheLuceneIndexCoalescedDeletes_2;
}

@end

void OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes_2 *self, OrgApacheLuceneIndexCoalescedDeletes *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
}

OrgApacheLuceneIndexCoalescedDeletes_2 *new_OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCoalescedDeletes_2, initWithOrgApacheLuceneIndexCoalescedDeletes_, outer$)
}

OrgApacheLuceneIndexCoalescedDeletes_2 *create_OrgApacheLuceneIndexCoalescedDeletes_2_initWithOrgApacheLuceneIndexCoalescedDeletes_(OrgApacheLuceneIndexCoalescedDeletes *outer$) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCoalescedDeletes_2, initWithOrgApacheLuceneIndexCoalescedDeletes_, outer$)
}

@implementation OrgApacheLuceneIndexCoalescedDeletes_2_1

- (instancetype)initWithOrgApacheLuceneIndexCoalescedDeletes_2:(OrgApacheLuceneIndexCoalescedDeletes_2 *)outer$ {
  OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(self, outer$);
  return self;
}

- (jboolean)hasNext {
  return [((id<JavaUtilIterator>) nil_chk(iter_)) hasNext];
}

- (OrgApacheLuceneIndexBufferedDeletesStream_QueryAndLimit *)next {
  id<JavaUtilMap_Entry> ent = [((id<JavaUtilIterator>) nil_chk(iter_)) next];
  return create_OrgApacheLuceneIndexBufferedDeletesStream_QueryAndLimit_initWithOrgApacheLuceneSearchQuery_withInt_([((id<JavaUtilMap_Entry>) nil_chk(ent)) getKey], [((JavaLangInteger *) nil_chk([ent getValue])) intValue]);
}

- (void)remove {
  @throw create_JavaLangUnsupportedOperationException_init();
}

- (void)forEachRemainingWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)arg0 {
  JavaUtilIterator_forEachRemainingWithJavaUtilFunctionConsumer_(self, arg0);
}

- (void)dealloc {
  RELEASE_(iter_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneIndexBufferedDeletesStream_QueryAndLimit;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneIndexCoalescedDeletes_2:);
  methods[1].selector = @selector(hasNext);
  methods[2].selector = @selector(next);
  methods[3].selector = @selector(remove);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "iter_", "LJavaUtilIterator;", .constantValue.asLong = 0, 0x12, -1, -1, 0, -1 },
  };
  static const void *ptrTable[] = { "Ljava/util/Iterator<Ljava/util/Map$Entry<Lorg/apache/lucene/search/Query;Ljava/lang/Integer;>;>;", "LOrgApacheLuceneIndexCoalescedDeletes_2;", "iterator", "Ljava/lang/Object;Ljava/util/Iterator<Lorg/apache/lucene/index/BufferedDeletesStream$QueryAndLimit;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCoalescedDeletes_2_1 = { "", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x8018, 4, 1, 1, -1, 2, 3, -1 };
  return &_OrgApacheLuceneIndexCoalescedDeletes_2_1;
}

@end

void OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(OrgApacheLuceneIndexCoalescedDeletes_2_1 *self, OrgApacheLuceneIndexCoalescedDeletes_2 *outer$) {
  NSObject_init(self);
  JreStrongAssign(&self->iter_, [((id<JavaUtilSet>) nil_chk([((id<JavaUtilMap>) nil_chk(outer$->this$0_->queries_)) entrySet])) iterator]);
}

OrgApacheLuceneIndexCoalescedDeletes_2_1 *new_OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(OrgApacheLuceneIndexCoalescedDeletes_2 *outer$) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCoalescedDeletes_2_1, initWithOrgApacheLuceneIndexCoalescedDeletes_2_, outer$)
}

OrgApacheLuceneIndexCoalescedDeletes_2_1 *create_OrgApacheLuceneIndexCoalescedDeletes_2_1_initWithOrgApacheLuceneIndexCoalescedDeletes_2_(OrgApacheLuceneIndexCoalescedDeletes_2 *outer$) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCoalescedDeletes_2_1, initWithOrgApacheLuceneIndexCoalescedDeletes_2_, outer$)
}

@implementation OrgApacheLuceneIndexCoalescedDeletes_3

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)capture$0 {
  OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(self, capture$0);
  return self;
}

- (jboolean)hasNext {
  if ([((OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *) nil_chk(queue_)) size] > 0) {
    return true;
  }
  for (jint i = 0; i < numTop_; i++) {
    if ([((id<JavaUtilIterator>) nil_chk(((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(IOSObjectArray_Get(nil_chk(top_), i)))->iterator_)) hasNext]) {
      return true;
    }
  }
  return false;
}

- (OrgApacheLuceneIndexTerm *)next {
  OrgApacheLuceneIndexCoalescedDeletes_3_pushTop(self);
  if ([((OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *) nil_chk(queue_)) size] > 0) {
    OrgApacheLuceneIndexCoalescedDeletes_3_pullTop(self);
  }
  else {
    JreStrongAssign(&current_, nil);
  }
  return current_;
}

- (void)remove {
  @throw create_JavaLangUnsupportedOperationException_init();
}

- (void)pullTop {
  OrgApacheLuceneIndexCoalescedDeletes_3_pullTop(self);
}

- (void)pushTop {
  OrgApacheLuceneIndexCoalescedDeletes_3_pushTop(self);
}

- (void)forEachRemainingWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)arg0 {
  JavaUtilIterator_forEachRemainingWithJavaUtilFunctionConsumer_(self, arg0);
}

- (void)dealloc {
  RELEASE_(current_);
  RELEASE_(queue_);
  RELEASE_(top_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneIndexTerm;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaUtilList:);
  methods[1].selector = @selector(hasNext);
  methods[2].selector = @selector(next);
  methods[3].selector = @selector(remove);
  methods[4].selector = @selector(pullTop);
  methods[5].selector = @selector(pushTop);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "current_", "LOrgApacheLuceneIndexTerm;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "queue_", "LOrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "top_", "[LOrgApacheLuceneIndexCoalescedDeletes_SubIterator;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "numTop_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneIndexCoalescedDeletes;", "mergedIteratorWithJavaUtilList:", "Ljava/lang/Object;Ljava/util/Iterator<Lorg/apache/lucene/index/Term;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCoalescedDeletes_3 = { "", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x8018, 6, 4, 0, -1, 1, 2, -1 };
  return &_OrgApacheLuceneIndexCoalescedDeletes_3;
}

@end

void OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(OrgApacheLuceneIndexCoalescedDeletes_3 *self, id<JavaUtilList> capture$0) {
  NSObject_init(self);
  JreStrongAssignAndConsume(&self->queue_, new_OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_([((id<JavaUtilList>) nil_chk(capture$0)) size]));
  JreStrongAssignAndConsume(&self->top_, [IOSObjectArray newArrayWithLength:[capture$0 size] type:OrgApacheLuceneIndexCoalescedDeletes_SubIterator_class_()]);
  {
    jint index = 0;
    for (id<JavaUtilIterator> __strong iterator in capture$0) {
      if ([((id<JavaUtilIterator>) nil_chk(iterator)) hasNext]) {
        OrgApacheLuceneIndexCoalescedDeletes_SubIterator *sub = create_OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init();
        JreStrongAssign(&sub->current_, [iterator next]);
        JreStrongAssign(&sub->iterator_, iterator);
        sub->index_ = index++;
        [((OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *) nil_chk(self->queue_)) addWithId:sub];
      }
    }
  }
}

OrgApacheLuceneIndexCoalescedDeletes_3 *new_OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(id<JavaUtilList> capture$0) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCoalescedDeletes_3, initWithJavaUtilList_, capture$0)
}

OrgApacheLuceneIndexCoalescedDeletes_3 *create_OrgApacheLuceneIndexCoalescedDeletes_3_initWithJavaUtilList_(id<JavaUtilList> capture$0) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCoalescedDeletes_3, initWithJavaUtilList_, capture$0)
}

void OrgApacheLuceneIndexCoalescedDeletes_3_pullTop(OrgApacheLuceneIndexCoalescedDeletes_3 *self) {
  JreAssert((self->numTop_ == 0), (@"org/apache/lucene/index/CoalescedDeletes.java:138 condition failed: assert numTop == 0;"));
  while (true) {
    IOSObjectArray_Set(nil_chk(self->top_), self->numTop_++, [((OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *) nil_chk(self->queue_)) pop]);
    if ([((OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *) nil_chk(self->queue_)) size] == 0 || ![((OrgApacheLuceneIndexTerm *) nil_chk(((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(([((OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *) nil_chk(self->queue_)) top])))->current_)) isEqual:((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(IOSObjectArray_Get(nil_chk(self->top_), 0)))->current_]) {
      break;
    }
  }
  JreStrongAssign(&self->current_, ((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(IOSObjectArray_Get(nil_chk(self->top_), 0)))->current_);
}

void OrgApacheLuceneIndexCoalescedDeletes_3_pushTop(OrgApacheLuceneIndexCoalescedDeletes_3 *self) {
  for (jint i = 0; i < self->numTop_; i++) {
    if ([((id<JavaUtilIterator>) nil_chk(((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(IOSObjectArray_Get(nil_chk(self->top_), i)))->iterator_)) hasNext]) {
      JreStrongAssign(&((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(IOSObjectArray_Get(nil_chk(self->top_), i)))->current_, [((id<JavaUtilIterator>) nil_chk(((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(IOSObjectArray_Get(self->top_, i)))->iterator_)) next]);
      [((OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *) nil_chk(self->queue_)) addWithId:IOSObjectArray_Get(nil_chk(self->top_), i)];
    }
    else {
      JreStrongAssign(&((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(IOSObjectArray_Get(nil_chk(self->top_), i)))->current_, nil);
    }
  }
  self->numTop_ = 0;
}

@implementation OrgApacheLuceneIndexCoalescedDeletes_SubIterator

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(iterator_);
  RELEASE_(current_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "iterator_", "LJavaUtilIterator;", .constantValue.asLong = 0, 0x0, -1, -1, 0, -1 },
    { "current_", "LOrgApacheLuceneIndexTerm;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "index_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "Ljava/util/Iterator<Lorg/apache/lucene/index/Term;>;", "LOrgApacheLuceneIndexCoalescedDeletes;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCoalescedDeletes_SubIterator = { "SubIterator", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0xa, 1, 3, 1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneIndexCoalescedDeletes_SubIterator;
}

@end

void OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *self) {
  NSObject_init(self);
}

OrgApacheLuceneIndexCoalescedDeletes_SubIterator *new_OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCoalescedDeletes_SubIterator, init)
}

OrgApacheLuceneIndexCoalescedDeletes_SubIterator *create_OrgApacheLuceneIndexCoalescedDeletes_SubIterator_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCoalescedDeletes_SubIterator, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneIndexCoalescedDeletes_SubIterator)

@implementation OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue

- (instancetype)initWithInt:(jint)size {
  OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_(self, size);
  return self;
}

- (jboolean)lessThanWithId:(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)a
                    withId:(OrgApacheLuceneIndexCoalescedDeletes_SubIterator *)b {
  jint cmp = [((OrgApacheLuceneIndexTerm *) nil_chk(((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(a))->current_)) compareToWithId:((OrgApacheLuceneIndexCoalescedDeletes_SubIterator *) nil_chk(b))->current_];
  if (cmp != 0) {
    return cmp < 0;
  }
  else {
    return a->index_ < b->index_;
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "Z", 0x4, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithInt:);
  methods[1].selector = @selector(lessThanWithId:withId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "I", "lessThan", "LOrgApacheLuceneIndexCoalescedDeletes_SubIterator;LOrgApacheLuceneIndexCoalescedDeletes_SubIterator;", "LOrgApacheLuceneIndexCoalescedDeletes;", "Lorg/apache/lucene/util/PriorityQueue<Lorg/apache/lucene/index/CoalescedDeletes$SubIterator;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue = { "TermMergeQueue", "org.apache.lucene.index", ptrTable, methods, NULL, 7, 0xa, 2, 0, 3, -1, -1, 4, -1 };
  return &_OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue;
}

@end

void OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_(OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *self, jint size) {
  OrgApacheLuceneUtilPriorityQueue_init(self);
  [self initialize__WithInt:size];
}

OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *new_OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_(jint size) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue, initWithInt_, size)
}

OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue *create_OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue_initWithInt_(jint size) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue, initWithInt_, size)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneIndexCoalescedDeletes_TermMergeQueue)
