//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/index/CompoundFileWriter.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/io/Closeable.h"
#include "java/io/IOException.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/NullPointerException.h"
#include "java/util/HashSet.h"
#include "java/util/LinkedList.h"
#include "org/apache/lucene/index/CompoundFileWriter.h"
#include "org/apache/lucene/index/IndexFileNames.h"
#include "org/apache/lucene/index/SegmentMerger.h"
#include "org/apache/lucene/store/Directory.h"
#include "org/apache/lucene/store/IndexInput.h"
#include "org/apache/lucene/store/IndexOutput.h"
#include "org/apache/lucene/util/IOUtils.h"

@class OrgApacheLuceneIndexCompoundFileWriter_FileEntry;

@interface OrgApacheLuceneIndexCompoundFileWriter () {
 @public
  OrgApacheLuceneStoreDirectory *directory_;
  NSString *fileName_;
  JavaUtilHashSet *ids_;
  JavaUtilLinkedList *entries_;
  jboolean merged_;
  OrgApacheLuceneIndexSegmentMerger_CheckAbort *checkAbort_;
}

- (void)copyFileWithOrgApacheLuceneIndexCompoundFileWriter_FileEntry:(OrgApacheLuceneIndexCompoundFileWriter_FileEntry *)source
                                 withOrgApacheLuceneStoreIndexOutput:(OrgApacheLuceneStoreIndexOutput *)os OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCompoundFileWriter, directory_, OrgApacheLuceneStoreDirectory *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCompoundFileWriter, fileName_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCompoundFileWriter, ids_, JavaUtilHashSet *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCompoundFileWriter, entries_, JavaUtilLinkedList *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCompoundFileWriter, checkAbort_, OrgApacheLuceneIndexSegmentMerger_CheckAbort *)

__attribute__((unused)) static void OrgApacheLuceneIndexCompoundFileWriter_copyFileWithOrgApacheLuceneIndexCompoundFileWriter_FileEntry_withOrgApacheLuceneStoreIndexOutput_(OrgApacheLuceneIndexCompoundFileWriter *self, OrgApacheLuceneIndexCompoundFileWriter_FileEntry *source, OrgApacheLuceneStoreIndexOutput *os);

@interface OrgApacheLuceneIndexCompoundFileWriter_FileEntry : NSObject {
 @public
  NSString *file_;
  jlong directoryOffset_;
  jlong dataOffset_;
  OrgApacheLuceneStoreDirectory *dir_;
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexCompoundFileWriter_FileEntry)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCompoundFileWriter_FileEntry, file_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexCompoundFileWriter_FileEntry, dir_, OrgApacheLuceneStoreDirectory *)

__attribute__((unused)) static void OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init(OrgApacheLuceneIndexCompoundFileWriter_FileEntry *self);

__attribute__((unused)) static OrgApacheLuceneIndexCompoundFileWriter_FileEntry *new_OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexCompoundFileWriter_FileEntry *create_OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexCompoundFileWriter_FileEntry)

@implementation OrgApacheLuceneIndexCompoundFileWriter

- (instancetype)initWithOrgApacheLuceneStoreDirectory:(OrgApacheLuceneStoreDirectory *)dir
                                         withNSString:(NSString *)name {
  OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_(self, dir, name);
  return self;
}

- (instancetype)initWithOrgApacheLuceneStoreDirectory:(OrgApacheLuceneStoreDirectory *)dir
                                         withNSString:(NSString *)name
     withOrgApacheLuceneIndexSegmentMerger_CheckAbort:(OrgApacheLuceneIndexSegmentMerger_CheckAbort *)checkAbort {
  OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_withOrgApacheLuceneIndexSegmentMerger_CheckAbort_(self, dir, name, checkAbort);
  return self;
}

- (OrgApacheLuceneStoreDirectory *)getDirectory {
  return directory_;
}

- (NSString *)getName {
  return fileName_;
}

- (void)addFileWithNSString:(NSString *)file {
  [self addFileWithNSString:file withOrgApacheLuceneStoreDirectory:directory_];
}

- (void)addFileWithNSString:(NSString *)file
withOrgApacheLuceneStoreDirectory:(OrgApacheLuceneStoreDirectory *)dir {
  if (merged_) @throw create_JavaLangIllegalStateException_initWithNSString_(@"Can't add extensions after merge has been called");
  if (file == nil) @throw create_JavaLangNullPointerException_initWithNSString_(@"file cannot be null");
  if (![((JavaUtilHashSet *) nil_chk(ids_)) addWithId:file]) @throw create_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("$$$", @"File ", file, @" already added"));
  OrgApacheLuceneIndexCompoundFileWriter_FileEntry *entry_ = create_OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init();
  JreStrongAssign(&entry_->file_, file);
  JreStrongAssign(&entry_->dir_, dir);
  [((JavaUtilLinkedList *) nil_chk(entries_)) addWithId:entry_];
}

- (void)close {
  if (merged_) @throw create_JavaLangIllegalStateException_initWithNSString_(@"Merge already performed");
  if ([((JavaUtilLinkedList *) nil_chk(entries_)) isEmpty]) @throw create_JavaLangIllegalStateException_initWithNSString_(@"No entries to merge have been defined");
  merged_ = true;
  OrgApacheLuceneStoreIndexOutput *os = [((OrgApacheLuceneStoreDirectory *) nil_chk(directory_)) createOutputWithNSString:fileName_];
  JavaIoIOException *priorException = nil;
  @try {
    [((OrgApacheLuceneStoreIndexOutput *) nil_chk(os)) writeVIntWithInt:OrgApacheLuceneIndexCompoundFileWriter_FORMAT_CURRENT];
    [os writeVIntWithInt:[((JavaUtilLinkedList *) nil_chk(entries_)) size]];
    jlong totalSize = 0;
    for (OrgApacheLuceneIndexCompoundFileWriter_FileEntry * __strong fe in nil_chk(entries_)) {
      ((OrgApacheLuceneIndexCompoundFileWriter_FileEntry *) nil_chk(fe))->directoryOffset_ = [os getFilePointer];
      [os writeLongWithLong:0];
      [os writeStringWithNSString:OrgApacheLuceneIndexIndexFileNames_stripSegmentNameWithNSString_(fe->file_)];
      totalSize += [((OrgApacheLuceneStoreDirectory *) nil_chk(fe->dir_)) fileLengthWithNSString:fe->file_];
    }
    jlong finalLength = totalSize + [os getFilePointer];
    [os setLengthWithLong:finalLength];
    for (OrgApacheLuceneIndexCompoundFileWriter_FileEntry * __strong fe in nil_chk(entries_)) {
      ((OrgApacheLuceneIndexCompoundFileWriter_FileEntry *) nil_chk(fe))->dataOffset_ = [os getFilePointer];
      OrgApacheLuceneIndexCompoundFileWriter_copyFileWithOrgApacheLuceneIndexCompoundFileWriter_FileEntry_withOrgApacheLuceneStoreIndexOutput_(self, fe, os);
    }
    for (OrgApacheLuceneIndexCompoundFileWriter_FileEntry * __strong fe in entries_) {
      [os seekWithLong:((OrgApacheLuceneIndexCompoundFileWriter_FileEntry *) nil_chk(fe))->directoryOffset_];
      [os writeLongWithLong:fe->dataOffset_];
    }
    JreAssert((finalLength == [os length]), (@"org/apache/lucene/index/CompoundFileWriter.java:210 condition failed: assert finalLength == os.length();"));
    OrgApacheLuceneStoreIndexOutput *tmp = os;
    os = nil;
    [tmp close];
  }
  @catch (JavaIoIOException *e) {
    priorException = e;
  }
  @finally {
    OrgApacheLuceneUtilIOUtils_closeWhileHandlingExceptionWithJavaLangException_withJavaIoCloseableArray_(priorException, [IOSObjectArray arrayWithObjects:(id[]){ os } count:1 type:JavaIoCloseable_class_()]);
  }
}

- (void)copyFileWithOrgApacheLuceneIndexCompoundFileWriter_FileEntry:(OrgApacheLuceneIndexCompoundFileWriter_FileEntry *)source
                                 withOrgApacheLuceneStoreIndexOutput:(OrgApacheLuceneStoreIndexOutput *)os {
  OrgApacheLuceneIndexCompoundFileWriter_copyFileWithOrgApacheLuceneIndexCompoundFileWriter_FileEntry_withOrgApacheLuceneStoreIndexOutput_(self, source, os);
}

- (void)dealloc {
  RELEASE_(directory_);
  RELEASE_(fileName_);
  RELEASE_(ids_);
  RELEASE_(entries_);
  RELEASE_(checkAbort_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneStoreDirectory;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 5, -1, -1, -1 },
    { NULL, "V", 0x2, 6, 7, 5, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneStoreDirectory:withNSString:);
  methods[1].selector = @selector(initWithOrgApacheLuceneStoreDirectory:withNSString:withOrgApacheLuceneIndexSegmentMerger_CheckAbort:);
  methods[2].selector = @selector(getDirectory);
  methods[3].selector = @selector(getName);
  methods[4].selector = @selector(addFileWithNSString:);
  methods[5].selector = @selector(addFileWithNSString:withOrgApacheLuceneStoreDirectory:);
  methods[6].selector = @selector(close);
  methods[7].selector = @selector(copyFileWithOrgApacheLuceneIndexCompoundFileWriter_FileEntry:withOrgApacheLuceneStoreIndexOutput:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "FORMAT_PRE_VERSION", "I", .constantValue.asInt = OrgApacheLuceneIndexCompoundFileWriter_FORMAT_PRE_VERSION, 0x18, -1, -1, -1, -1 },
    { "FORMAT_NO_SEGMENT_PREFIX", "I", .constantValue.asInt = OrgApacheLuceneIndexCompoundFileWriter_FORMAT_NO_SEGMENT_PREFIX, 0x18, -1, -1, -1, -1 },
    { "FORMAT_CURRENT", "I", .constantValue.asInt = OrgApacheLuceneIndexCompoundFileWriter_FORMAT_CURRENT, 0x18, -1, -1, -1, -1 },
    { "directory_", "LOrgApacheLuceneStoreDirectory;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "fileName_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "ids_", "LJavaUtilHashSet;", .constantValue.asLong = 0, 0x2, -1, -1, 8, -1 },
    { "entries_", "LJavaUtilLinkedList;", .constantValue.asLong = 0, 0x2, -1, -1, 9, -1 },
    { "merged_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "checkAbort_", "LOrgApacheLuceneIndexSegmentMerger_CheckAbort;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneStoreDirectory;LNSString;", "LOrgApacheLuceneStoreDirectory;LNSString;LOrgApacheLuceneIndexSegmentMerger_CheckAbort;", "addFile", "LNSString;", "LNSString;LOrgApacheLuceneStoreDirectory;", "LJavaIoIOException;", "copyFile", "LOrgApacheLuceneIndexCompoundFileWriter_FileEntry;LOrgApacheLuceneStoreIndexOutput;", "Ljava/util/HashSet<Ljava/lang/String;>;", "Ljava/util/LinkedList<Lorg/apache/lucene/index/CompoundFileWriter$FileEntry;>;", "LOrgApacheLuceneIndexCompoundFileWriter_FileEntry;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCompoundFileWriter = { "CompoundFileWriter", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x11, 8, 9, -1, 10, -1, -1, -1 };
  return &_OrgApacheLuceneIndexCompoundFileWriter;
}

@end

void OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_(OrgApacheLuceneIndexCompoundFileWriter *self, OrgApacheLuceneStoreDirectory *dir, NSString *name) {
  OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_withOrgApacheLuceneIndexSegmentMerger_CheckAbort_(self, dir, name, nil);
}

OrgApacheLuceneIndexCompoundFileWriter *new_OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_(OrgApacheLuceneStoreDirectory *dir, NSString *name) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCompoundFileWriter, initWithOrgApacheLuceneStoreDirectory_withNSString_, dir, name)
}

OrgApacheLuceneIndexCompoundFileWriter *create_OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_(OrgApacheLuceneStoreDirectory *dir, NSString *name) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCompoundFileWriter, initWithOrgApacheLuceneStoreDirectory_withNSString_, dir, name)
}

void OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_withOrgApacheLuceneIndexSegmentMerger_CheckAbort_(OrgApacheLuceneIndexCompoundFileWriter *self, OrgApacheLuceneStoreDirectory *dir, NSString *name, OrgApacheLuceneIndexSegmentMerger_CheckAbort *checkAbort) {
  NSObject_init(self);
  self->merged_ = false;
  if (dir == nil) @throw create_JavaLangNullPointerException_initWithNSString_(@"directory cannot be null");
  if (name == nil) @throw create_JavaLangNullPointerException_initWithNSString_(@"name cannot be null");
  JreStrongAssign(&self->checkAbort_, checkAbort);
  JreStrongAssign(&self->directory_, dir);
  JreStrongAssign(&self->fileName_, name);
  JreStrongAssignAndConsume(&self->ids_, new_JavaUtilHashSet_init());
  JreStrongAssignAndConsume(&self->entries_, new_JavaUtilLinkedList_init());
}

OrgApacheLuceneIndexCompoundFileWriter *new_OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_withOrgApacheLuceneIndexSegmentMerger_CheckAbort_(OrgApacheLuceneStoreDirectory *dir, NSString *name, OrgApacheLuceneIndexSegmentMerger_CheckAbort *checkAbort) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCompoundFileWriter, initWithOrgApacheLuceneStoreDirectory_withNSString_withOrgApacheLuceneIndexSegmentMerger_CheckAbort_, dir, name, checkAbort)
}

OrgApacheLuceneIndexCompoundFileWriter *create_OrgApacheLuceneIndexCompoundFileWriter_initWithOrgApacheLuceneStoreDirectory_withNSString_withOrgApacheLuceneIndexSegmentMerger_CheckAbort_(OrgApacheLuceneStoreDirectory *dir, NSString *name, OrgApacheLuceneIndexSegmentMerger_CheckAbort *checkAbort) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCompoundFileWriter, initWithOrgApacheLuceneStoreDirectory_withNSString_withOrgApacheLuceneIndexSegmentMerger_CheckAbort_, dir, name, checkAbort)
}

void OrgApacheLuceneIndexCompoundFileWriter_copyFileWithOrgApacheLuceneIndexCompoundFileWriter_FileEntry_withOrgApacheLuceneStoreIndexOutput_(OrgApacheLuceneIndexCompoundFileWriter *self, OrgApacheLuceneIndexCompoundFileWriter_FileEntry *source, OrgApacheLuceneStoreIndexOutput *os) {
  OrgApacheLuceneStoreIndexInput *is = [((OrgApacheLuceneStoreDirectory *) nil_chk(((OrgApacheLuceneIndexCompoundFileWriter_FileEntry *) nil_chk(source))->dir_)) openInputWithNSString:source->file_];
  @try {
    jlong startPtr = [((OrgApacheLuceneStoreIndexOutput *) nil_chk(os)) getFilePointer];
    jlong length = [((OrgApacheLuceneStoreIndexInput *) nil_chk(is)) length];
    [os copyBytesWithOrgApacheLuceneStoreDataInput:is withLong:length];
    if (self->checkAbort_ != nil) {
      [self->checkAbort_ workWithDouble:length];
    }
    jlong endPtr = [os getFilePointer];
    jlong diff = endPtr - startPtr;
    if (diff != length) @throw create_JavaIoIOException_initWithNSString_(JreStrcat("$J$J", @"Difference in the output file offsets ", diff, @" does not match the original file length ", length));
  }
  @finally {
    [((OrgApacheLuceneStoreIndexInput *) nil_chk(is)) close];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneIndexCompoundFileWriter)

@implementation OrgApacheLuceneIndexCompoundFileWriter_FileEntry

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(file_);
  RELEASE_(dir_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "file_", "LNSString;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "directoryOffset_", "J", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "dataOffset_", "J", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "dir_", "LOrgApacheLuceneStoreDirectory;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneIndexCompoundFileWriter;" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexCompoundFileWriter_FileEntry = { "FileEntry", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x1a, 1, 4, 0, -1, -1, -1, -1 };
  return &_OrgApacheLuceneIndexCompoundFileWriter_FileEntry;
}

@end

void OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init(OrgApacheLuceneIndexCompoundFileWriter_FileEntry *self) {
  NSObject_init(self);
}

OrgApacheLuceneIndexCompoundFileWriter_FileEntry *new_OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexCompoundFileWriter_FileEntry, init)
}

OrgApacheLuceneIndexCompoundFileWriter_FileEntry *create_OrgApacheLuceneIndexCompoundFileWriter_FileEntry_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexCompoundFileWriter_FileEntry, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneIndexCompoundFileWriter_FileEntry)
