//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/index/IndexDeletionPolicy.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/index/IndexDeletionPolicy.h"

@interface OrgApacheLuceneIndexIndexDeletionPolicy : NSObject

@end

@implementation OrgApacheLuceneIndexIndexDeletionPolicy

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, 2, 3, -1, -1 },
    { NULL, "V", 0x401, 4, 1, 2, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(onInitWithJavaUtilList:);
  methods[1].selector = @selector(onCommitWithJavaUtilList:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "onInit", "LJavaUtilList;", "LJavaIoIOException;", "(Ljava/util/List<+Lorg/apache/lucene/index/IndexCommit;>;)V", "onCommit" };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexIndexDeletionPolicy = { "IndexDeletionPolicy", "org.apache.lucene.index", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneIndexIndexDeletionPolicy;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneIndexIndexDeletionPolicy)
