//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/index/NoMergePolicy.java
//

#include "J2ObjC_source.h"
#include "java/util/Map.h"
#include "org/apache/lucene/index/IndexWriter.h"
#include "org/apache/lucene/index/MergePolicy.h"
#include "org/apache/lucene/index/NoMergePolicy.h"
#include "org/apache/lucene/index/SegmentInfo.h"
#include "org/apache/lucene/index/SegmentInfos.h"

@interface OrgApacheLuceneIndexNoMergePolicy () {
 @public
  jboolean useCompoundFile_;
}

- (instancetype)initWithBoolean:(jboolean)useCompoundFile;

@end

__attribute__((unused)) static void OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(OrgApacheLuceneIndexNoMergePolicy *self, jboolean useCompoundFile);

__attribute__((unused)) static OrgApacheLuceneIndexNoMergePolicy *new_OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(jboolean useCompoundFile) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneIndexNoMergePolicy *create_OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(jboolean useCompoundFile);

J2OBJC_INITIALIZED_DEFN(OrgApacheLuceneIndexNoMergePolicy)

OrgApacheLuceneIndexMergePolicy *OrgApacheLuceneIndexNoMergePolicy_NO_COMPOUND_FILES;
OrgApacheLuceneIndexMergePolicy *OrgApacheLuceneIndexNoMergePolicy_COMPOUND_FILES;

@implementation OrgApacheLuceneIndexNoMergePolicy

- (instancetype)initWithBoolean:(jboolean)useCompoundFile {
  OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(self, useCompoundFile);
  return self;
}

- (void)close {
}

- (OrgApacheLuceneIndexMergePolicy_MergeSpecification *)findMergesWithOrgApacheLuceneIndexSegmentInfos:(OrgApacheLuceneIndexSegmentInfos *)segmentInfos {
  return nil;
}

- (OrgApacheLuceneIndexMergePolicy_MergeSpecification *)findForcedMergesWithOrgApacheLuceneIndexSegmentInfos:(OrgApacheLuceneIndexSegmentInfos *)segmentInfos
                                                                                                     withInt:(jint)maxSegmentCount
                                                                                             withJavaUtilMap:(id<JavaUtilMap>)segmentsToMerge {
  return nil;
}

- (OrgApacheLuceneIndexMergePolicy_MergeSpecification *)findForcedDeletesMergesWithOrgApacheLuceneIndexSegmentInfos:(OrgApacheLuceneIndexSegmentInfos *)segmentInfos {
  return nil;
}

- (jboolean)useCompoundFileWithOrgApacheLuceneIndexSegmentInfos:(OrgApacheLuceneIndexSegmentInfos *)segments
                            withOrgApacheLuceneIndexSegmentInfo:(OrgApacheLuceneIndexSegmentInfo *)newSegment {
  return useCompoundFile_;
}

- (void)setIndexWriterWithOrgApacheLuceneIndexIndexWriter:(OrgApacheLuceneIndexIndexWriter *)writer {
}

- (NSString *)description {
  return @"NoMergePolicy";
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneIndexMergePolicy_MergeSpecification;", 0x1, 1, 2, 3, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneIndexMergePolicy_MergeSpecification;", 0x1, 4, 5, 3, 6, -1, -1 },
    { NULL, "LOrgApacheLuceneIndexMergePolicy_MergeSpecification;", 0x1, 7, 2, 3, -1, -1, -1 },
    { NULL, "Z", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 12, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithBoolean:);
  methods[1].selector = @selector(close);
  methods[2].selector = @selector(findMergesWithOrgApacheLuceneIndexSegmentInfos:);
  methods[3].selector = @selector(findForcedMergesWithOrgApacheLuceneIndexSegmentInfos:withInt:withJavaUtilMap:);
  methods[4].selector = @selector(findForcedDeletesMergesWithOrgApacheLuceneIndexSegmentInfos:);
  methods[5].selector = @selector(useCompoundFileWithOrgApacheLuceneIndexSegmentInfos:withOrgApacheLuceneIndexSegmentInfo:);
  methods[6].selector = @selector(setIndexWriterWithOrgApacheLuceneIndexIndexWriter:);
  methods[7].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "NO_COMPOUND_FILES", "LOrgApacheLuceneIndexMergePolicy;", .constantValue.asLong = 0, 0x19, -1, 13, -1, -1 },
    { "COMPOUND_FILES", "LOrgApacheLuceneIndexMergePolicy;", .constantValue.asLong = 0, 0x19, -1, 14, -1, -1 },
    { "useCompoundFile_", "Z", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "Z", "findMerges", "LOrgApacheLuceneIndexSegmentInfos;", "LOrgApacheLuceneIndexCorruptIndexException;LJavaIoIOException;", "findForcedMerges", "LOrgApacheLuceneIndexSegmentInfos;ILJavaUtilMap;", "(Lorg/apache/lucene/index/SegmentInfos;ILjava/util/Map<Lorg/apache/lucene/index/SegmentInfo;Ljava/lang/Boolean;>;)Lorg/apache/lucene/index/MergePolicy$MergeSpecification;", "findForcedDeletesMerges", "useCompoundFile", "LOrgApacheLuceneIndexSegmentInfos;LOrgApacheLuceneIndexSegmentInfo;", "setIndexWriter", "LOrgApacheLuceneIndexIndexWriter;", "toString", &OrgApacheLuceneIndexNoMergePolicy_NO_COMPOUND_FILES, &OrgApacheLuceneIndexNoMergePolicy_COMPOUND_FILES };
  static const J2ObjcClassInfo _OrgApacheLuceneIndexNoMergePolicy = { "NoMergePolicy", "org.apache.lucene.index", ptrTable, methods, fields, 7, 0x11, 8, 3, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneIndexNoMergePolicy;
}

+ (void)initialize {
  if (self == [OrgApacheLuceneIndexNoMergePolicy class]) {
    JreStrongAssignAndConsume(&OrgApacheLuceneIndexNoMergePolicy_NO_COMPOUND_FILES, new_OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(false));
    JreStrongAssignAndConsume(&OrgApacheLuceneIndexNoMergePolicy_COMPOUND_FILES, new_OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(true));
    J2OBJC_SET_INITIALIZED(OrgApacheLuceneIndexNoMergePolicy)
  }
}

@end

void OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(OrgApacheLuceneIndexNoMergePolicy *self, jboolean useCompoundFile) {
  OrgApacheLuceneIndexMergePolicy_init(self);
  self->useCompoundFile_ = useCompoundFile;
}

OrgApacheLuceneIndexNoMergePolicy *new_OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(jboolean useCompoundFile) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneIndexNoMergePolicy, initWithBoolean_, useCompoundFile)
}

OrgApacheLuceneIndexNoMergePolicy *create_OrgApacheLuceneIndexNoMergePolicy_initWithBoolean_(jboolean useCompoundFile) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneIndexNoMergePolicy, initWithBoolean_, useCompoundFile)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneIndexNoMergePolicy)
