//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/index/TermVectorOffsetInfo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneIndexTermVectorOffsetInfo")
#ifdef RESTRICT_OrgApacheLuceneIndexTermVectorOffsetInfo
#define INCLUDE_ALL_OrgApacheLuceneIndexTermVectorOffsetInfo 0
#else
#define INCLUDE_ALL_OrgApacheLuceneIndexTermVectorOffsetInfo 1
#endif
#undef RESTRICT_OrgApacheLuceneIndexTermVectorOffsetInfo

#if !defined (OrgApacheLuceneIndexTermVectorOffsetInfo_) && (INCLUDE_ALL_OrgApacheLuceneIndexTermVectorOffsetInfo || defined(INCLUDE_OrgApacheLuceneIndexTermVectorOffsetInfo))
#define OrgApacheLuceneIndexTermVectorOffsetInfo_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class IOSObjectArray;

@interface OrgApacheLuceneIndexTermVectorOffsetInfo : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)startOffset
                    withInt:(jint)endOffset;

- (jboolean)isEqual:(id)o;

- (jint)getEndOffset;

- (jint)getStartOffset;

- (NSUInteger)hash;

- (void)setEndOffsetWithInt:(jint)endOffset;

- (void)setStartOffsetWithInt:(jint)startOffset;

@end

J2OBJC_STATIC_INIT(OrgApacheLuceneIndexTermVectorOffsetInfo)

inline IOSObjectArray *OrgApacheLuceneIndexTermVectorOffsetInfo_get_EMPTY_OFFSET_INFO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *OrgApacheLuceneIndexTermVectorOffsetInfo_EMPTY_OFFSET_INFO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneIndexTermVectorOffsetInfo, EMPTY_OFFSET_INFO, IOSObjectArray *)

FOUNDATION_EXPORT void OrgApacheLuceneIndexTermVectorOffsetInfo_init(OrgApacheLuceneIndexTermVectorOffsetInfo *self);

FOUNDATION_EXPORT OrgApacheLuceneIndexTermVectorOffsetInfo *new_OrgApacheLuceneIndexTermVectorOffsetInfo_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneIndexTermVectorOffsetInfo *create_OrgApacheLuceneIndexTermVectorOffsetInfo_init();

FOUNDATION_EXPORT void OrgApacheLuceneIndexTermVectorOffsetInfo_initWithInt_withInt_(OrgApacheLuceneIndexTermVectorOffsetInfo *self, jint startOffset, jint endOffset);

FOUNDATION_EXPORT OrgApacheLuceneIndexTermVectorOffsetInfo *new_OrgApacheLuceneIndexTermVectorOffsetInfo_initWithInt_withInt_(jint startOffset, jint endOffset) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneIndexTermVectorOffsetInfo *create_OrgApacheLuceneIndexTermVectorOffsetInfo_initWithInt_withInt_(jint startOffset, jint endOffset);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexTermVectorOffsetInfo)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneIndexTermVectorOffsetInfo")
