//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/index/PrefixCodedTerms.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneIndexPrefixCodedTerms")
#ifdef RESTRICT_OrgApacheLuceneIndexPrefixCodedTerms
#define INCLUDE_ALL_OrgApacheLuceneIndexPrefixCodedTerms 0
#else
#define INCLUDE_ALL_OrgApacheLuceneIndexPrefixCodedTerms 1
#endif
#undef RESTRICT_OrgApacheLuceneIndexPrefixCodedTerms

#if !defined (OrgApacheLuceneIndexPrefixCodedTerms_) && (INCLUDE_ALL_OrgApacheLuceneIndexPrefixCodedTerms || defined(INCLUDE_OrgApacheLuceneIndexPrefixCodedTerms))
#define OrgApacheLuceneIndexPrefixCodedTerms_

#define RESTRICT_JavaLangIterable 1
#define INCLUDE_JavaLangIterable 1
#include "java/lang/Iterable.h"

@class OrgApacheLuceneStoreRAMFile;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilIterator;
@protocol JavaUtilSpliterator;

@interface OrgApacheLuceneIndexPrefixCodedTerms : NSObject < JavaLangIterable > {
 @public
  OrgApacheLuceneStoreRAMFile *buffer_;
}

#pragma mark Public

- (jlong)getSizeInBytes;

- (id<JavaUtilIterator>)iterator;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexPrefixCodedTerms)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexPrefixCodedTerms, buffer_, OrgApacheLuceneStoreRAMFile *)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexPrefixCodedTerms)

#endif

#if !defined (OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator_) && (INCLUDE_ALL_OrgApacheLuceneIndexPrefixCodedTerms || defined(INCLUDE_OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator))
#define OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class OrgApacheLuceneIndexPrefixCodedTerms;
@class OrgApacheLuceneIndexTerm;
@class OrgApacheLuceneStoreIndexInput;
@class OrgApacheLuceneUtilBytesRef;
@protocol JavaUtilFunctionConsumer;

@interface OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator : NSObject < JavaUtilIterator > {
 @public
  OrgApacheLuceneStoreIndexInput *input_;
  NSString *field_;
  OrgApacheLuceneUtilBytesRef *bytes_;
  OrgApacheLuceneIndexTerm *term_;
}

#pragma mark Public

- (jboolean)hasNext;

- (OrgApacheLuceneIndexTerm *)next;

- (void)remove;

#pragma mark Package-Private

- (instancetype)initWithOrgApacheLuceneIndexPrefixCodedTerms:(OrgApacheLuceneIndexPrefixCodedTerms *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator, input_, OrgApacheLuceneStoreIndexInput *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator, field_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator, bytes_, OrgApacheLuceneUtilBytesRef *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator, term_, OrgApacheLuceneIndexTerm *)

FOUNDATION_EXPORT void OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator_initWithOrgApacheLuceneIndexPrefixCodedTerms_(OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator *self, OrgApacheLuceneIndexPrefixCodedTerms *outer$);

FOUNDATION_EXPORT OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator *new_OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator_initWithOrgApacheLuceneIndexPrefixCodedTerms_(OrgApacheLuceneIndexPrefixCodedTerms *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator *create_OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator_initWithOrgApacheLuceneIndexPrefixCodedTerms_(OrgApacheLuceneIndexPrefixCodedTerms *outer$);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexPrefixCodedTerms_PrefixCodedTermsIterator)

#endif

#if !defined (OrgApacheLuceneIndexPrefixCodedTerms_Builder_) && (INCLUDE_ALL_OrgApacheLuceneIndexPrefixCodedTerms || defined(INCLUDE_OrgApacheLuceneIndexPrefixCodedTerms_Builder))
#define OrgApacheLuceneIndexPrefixCodedTerms_Builder_

@class OrgApacheLuceneIndexPrefixCodedTerms;
@class OrgApacheLuceneIndexTerm;

@interface OrgApacheLuceneIndexPrefixCodedTerms_Builder : NSObject

#pragma mark Public

- (instancetype)init;

- (void)addWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term;

- (OrgApacheLuceneIndexPrefixCodedTerms *)finish;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexPrefixCodedTerms_Builder)

FOUNDATION_EXPORT void OrgApacheLuceneIndexPrefixCodedTerms_Builder_init(OrgApacheLuceneIndexPrefixCodedTerms_Builder *self);

FOUNDATION_EXPORT OrgApacheLuceneIndexPrefixCodedTerms_Builder *new_OrgApacheLuceneIndexPrefixCodedTerms_Builder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneIndexPrefixCodedTerms_Builder *create_OrgApacheLuceneIndexPrefixCodedTerms_Builder_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexPrefixCodedTerms_Builder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneIndexPrefixCodedTerms")
