//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/index/TermsHash.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneIndexTermsHash")
#ifdef RESTRICT_OrgApacheLuceneIndexTermsHash
#define INCLUDE_ALL_OrgApacheLuceneIndexTermsHash 0
#else
#define INCLUDE_ALL_OrgApacheLuceneIndexTermsHash 1
#endif
#undef RESTRICT_OrgApacheLuceneIndexTermsHash

#if !defined (OrgApacheLuceneIndexTermsHash_) && (INCLUDE_ALL_OrgApacheLuceneIndexTermsHash || defined(INCLUDE_OrgApacheLuceneIndexTermsHash))
#define OrgApacheLuceneIndexTermsHash_

#define RESTRICT_OrgApacheLuceneIndexInvertedDocConsumer 1
#define INCLUDE_OrgApacheLuceneIndexInvertedDocConsumer 1
#include "org/apache/lucene/index/InvertedDocConsumer.h"

@class OrgApacheLuceneIndexDocInverterPerThread;
@class OrgApacheLuceneIndexDocumentsWriter;
@class OrgApacheLuceneIndexFieldInfos;
@class OrgApacheLuceneIndexInvertedDocConsumerPerThread;
@class OrgApacheLuceneIndexSegmentWriteState;
@class OrgApacheLuceneIndexTermsHashConsumer;
@class OrgApacheLuceneIndexTermsHashPerThread;
@protocol JavaUtilMap;

@interface OrgApacheLuceneIndexTermsHash : OrgApacheLuceneIndexInvertedDocConsumer {
 @public
  OrgApacheLuceneIndexTermsHashConsumer *consumer_;
  OrgApacheLuceneIndexTermsHash *nextTermsHash_;
  OrgApacheLuceneIndexDocumentsWriter *docWriter_;
  jboolean trackAllocations_;
}

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneIndexDocumentsWriter:(OrgApacheLuceneIndexDocumentsWriter *)docWriter
                                                withBoolean:(jboolean)trackAllocations
                  withOrgApacheLuceneIndexTermsHashConsumer:(OrgApacheLuceneIndexTermsHashConsumer *)consumer
                          withOrgApacheLuceneIndexTermsHash:(OrgApacheLuceneIndexTermsHash *)nextTermsHash;

- (void)abort;

- (jboolean)freeRAM;

#pragma mark Package-Private

- (OrgApacheLuceneIndexInvertedDocConsumerPerThread *)addThreadWithOrgApacheLuceneIndexDocInverterPerThread:(OrgApacheLuceneIndexDocInverterPerThread *)docInverterPerThread;

- (OrgApacheLuceneIndexTermsHashPerThread *)addThreadWithOrgApacheLuceneIndexDocInverterPerThread:(OrgApacheLuceneIndexDocInverterPerThread *)docInverterPerThread
                                                       withOrgApacheLuceneIndexTermsHashPerThread:(OrgApacheLuceneIndexTermsHashPerThread *)primaryPerThread;

- (void)flushWithJavaUtilMap:(id<JavaUtilMap>)threadsAndFields
withOrgApacheLuceneIndexSegmentWriteState:(OrgApacheLuceneIndexSegmentWriteState *)state;

- (void)setFieldInfosWithOrgApacheLuceneIndexFieldInfos:(OrgApacheLuceneIndexFieldInfos *)fieldInfos;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneIndexTermsHash)

J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexTermsHash, consumer_, OrgApacheLuceneIndexTermsHashConsumer *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexTermsHash, nextTermsHash_, OrgApacheLuceneIndexTermsHash *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneIndexTermsHash, docWriter_, OrgApacheLuceneIndexDocumentsWriter *)

FOUNDATION_EXPORT void OrgApacheLuceneIndexTermsHash_initWithOrgApacheLuceneIndexDocumentsWriter_withBoolean_withOrgApacheLuceneIndexTermsHashConsumer_withOrgApacheLuceneIndexTermsHash_(OrgApacheLuceneIndexTermsHash *self, OrgApacheLuceneIndexDocumentsWriter *docWriter, jboolean trackAllocations, OrgApacheLuceneIndexTermsHashConsumer *consumer, OrgApacheLuceneIndexTermsHash *nextTermsHash);

FOUNDATION_EXPORT OrgApacheLuceneIndexTermsHash *new_OrgApacheLuceneIndexTermsHash_initWithOrgApacheLuceneIndexDocumentsWriter_withBoolean_withOrgApacheLuceneIndexTermsHashConsumer_withOrgApacheLuceneIndexTermsHash_(OrgApacheLuceneIndexDocumentsWriter *docWriter, jboolean trackAllocations, OrgApacheLuceneIndexTermsHashConsumer *consumer, OrgApacheLuceneIndexTermsHash *nextTermsHash) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneIndexTermsHash *create_OrgApacheLuceneIndexTermsHash_initWithOrgApacheLuceneIndexDocumentsWriter_withBoolean_withOrgApacheLuceneIndexTermsHashConsumer_withOrgApacheLuceneIndexTermsHash_(OrgApacheLuceneIndexDocumentsWriter *docWriter, jboolean trackAllocations, OrgApacheLuceneIndexTermsHashConsumer *consumer, OrgApacheLuceneIndexTermsHash *nextTermsHash);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneIndexTermsHash)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneIndexTermsHash")
