//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/util/Constants.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Deprecated.h"
#include "java/lang/NoSuchMethodException.h"
#include "java/lang/Package.h"
#include "java/lang/System.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/reflect/Method.h"
#include "org/apache/lucene/LucenePackage.h"
#include "org/apache/lucene/util/Constants.h"

@interface OrgApacheLuceneUtilConstants ()

- (instancetype)init;

+ (NSString *)identWithNSString:(NSString *)s;

@end

__attribute__((unused)) static void OrgApacheLuceneUtilConstants_init(OrgApacheLuceneUtilConstants *self);

__attribute__((unused)) static OrgApacheLuceneUtilConstants *new_OrgApacheLuceneUtilConstants_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneUtilConstants *create_OrgApacheLuceneUtilConstants_init();

__attribute__((unused)) static NSString *OrgApacheLuceneUtilConstants_identWithNSString_(NSString *s);

__attribute__((unused)) static IOSObjectArray *OrgApacheLuceneUtilConstants__Annotations$0();

__attribute__((unused)) static IOSObjectArray *OrgApacheLuceneUtilConstants__Annotations$1();

__attribute__((unused)) static IOSObjectArray *OrgApacheLuceneUtilConstants__Annotations$2();

J2OBJC_INITIALIZED_DEFN(OrgApacheLuceneUtilConstants)

NSString *OrgApacheLuceneUtilConstants_JAVA_VERSION;
jboolean OrgApacheLuceneUtilConstants_JAVA_1_1;
jboolean OrgApacheLuceneUtilConstants_JAVA_1_2;
jboolean OrgApacheLuceneUtilConstants_JAVA_1_3;
NSString *OrgApacheLuceneUtilConstants_OS_NAME;
jboolean OrgApacheLuceneUtilConstants_LINUX;
jboolean OrgApacheLuceneUtilConstants_WINDOWS;
jboolean OrgApacheLuceneUtilConstants_SUN_OS;
jboolean OrgApacheLuceneUtilConstants_MAC_OS_X;
NSString *OrgApacheLuceneUtilConstants_OS_ARCH;
NSString *OrgApacheLuceneUtilConstants_OS_VERSION;
NSString *OrgApacheLuceneUtilConstants_JAVA_VENDOR;
jboolean OrgApacheLuceneUtilConstants_JRE_IS_64BIT;
jboolean OrgApacheLuceneUtilConstants_JRE_IS_MINIMUM_JAVA6;
jboolean OrgApacheLuceneUtilConstants_JRE_IS_MINIMUM_JAVA7;
NSString *OrgApacheLuceneUtilConstants_LUCENE_MAIN_VERSION;
NSString *OrgApacheLuceneUtilConstants_LUCENE_VERSION;

@implementation OrgApacheLuceneUtilConstants

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneUtilConstants_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (NSString *)identWithNSString:(NSString *)s {
  return OrgApacheLuceneUtilConstants_identWithNSString_(s);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0xa, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(identWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "JAVA_VERSION", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 2, -1, -1 },
    { "JAVA_1_1", "Z", .constantValue.asLong = 0, 0x19, -1, 3, -1, 4 },
    { "JAVA_1_2", "Z", .constantValue.asLong = 0, 0x19, -1, 5, -1, 6 },
    { "JAVA_1_3", "Z", .constantValue.asLong = 0, 0x19, -1, 7, -1, 8 },
    { "OS_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 9, -1, -1 },
    { "LINUX", "Z", .constantValue.asLong = 0, 0x19, -1, 10, -1, -1 },
    { "WINDOWS", "Z", .constantValue.asLong = 0, 0x19, -1, 11, -1, -1 },
    { "SUN_OS", "Z", .constantValue.asLong = 0, 0x19, -1, 12, -1, -1 },
    { "MAC_OS_X", "Z", .constantValue.asLong = 0, 0x19, -1, 13, -1, -1 },
    { "OS_ARCH", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 14, -1, -1 },
    { "OS_VERSION", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 15, -1, -1 },
    { "JAVA_VENDOR", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 16, -1, -1 },
    { "JRE_IS_64BIT", "Z", .constantValue.asLong = 0, 0x19, -1, 17, -1, -1 },
    { "JRE_IS_MINIMUM_JAVA6", "Z", .constantValue.asLong = 0, 0x19, -1, 18, -1, -1 },
    { "JRE_IS_MINIMUM_JAVA7", "Z", .constantValue.asLong = 0, 0x19, -1, 19, -1, -1 },
    { "LUCENE_MAIN_VERSION", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 20, -1, -1 },
    { "LUCENE_VERSION", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 21, -1, -1 },
  };
  static const void *ptrTable[] = { "ident", "LNSString;", &OrgApacheLuceneUtilConstants_JAVA_VERSION, &OrgApacheLuceneUtilConstants_JAVA_1_1, (void *)&OrgApacheLuceneUtilConstants__Annotations$0, &OrgApacheLuceneUtilConstants_JAVA_1_2, (void *)&OrgApacheLuceneUtilConstants__Annotations$1, &OrgApacheLuceneUtilConstants_JAVA_1_3, (void *)&OrgApacheLuceneUtilConstants__Annotations$2, &OrgApacheLuceneUtilConstants_OS_NAME, &OrgApacheLuceneUtilConstants_LINUX, &OrgApacheLuceneUtilConstants_WINDOWS, &OrgApacheLuceneUtilConstants_SUN_OS, &OrgApacheLuceneUtilConstants_MAC_OS_X, &OrgApacheLuceneUtilConstants_OS_ARCH, &OrgApacheLuceneUtilConstants_OS_VERSION, &OrgApacheLuceneUtilConstants_JAVA_VENDOR, &OrgApacheLuceneUtilConstants_JRE_IS_64BIT, &OrgApacheLuceneUtilConstants_JRE_IS_MINIMUM_JAVA6, &OrgApacheLuceneUtilConstants_JRE_IS_MINIMUM_JAVA7, &OrgApacheLuceneUtilConstants_LUCENE_MAIN_VERSION, &OrgApacheLuceneUtilConstants_LUCENE_VERSION };
  static const J2ObjcClassInfo _OrgApacheLuceneUtilConstants = { "Constants", "org.apache.lucene.util", ptrTable, methods, fields, 7, 0x11, 2, 17, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneUtilConstants;
}

+ (void)initialize {
  if (self == [OrgApacheLuceneUtilConstants class]) {
    JreStrongAssign(&OrgApacheLuceneUtilConstants_JAVA_VERSION, JavaLangSystem_getPropertyWithNSString_(@"java.version"));
    OrgApacheLuceneUtilConstants_JAVA_1_1 = [((NSString *) nil_chk(OrgApacheLuceneUtilConstants_JAVA_VERSION)) java_hasPrefix:@"1.1."];
    OrgApacheLuceneUtilConstants_JAVA_1_2 = [OrgApacheLuceneUtilConstants_JAVA_VERSION java_hasPrefix:@"1.2."];
    OrgApacheLuceneUtilConstants_JAVA_1_3 = [OrgApacheLuceneUtilConstants_JAVA_VERSION java_hasPrefix:@"1.3."];
    JreStrongAssign(&OrgApacheLuceneUtilConstants_OS_NAME, JavaLangSystem_getPropertyWithNSString_(@"os.name"));
    OrgApacheLuceneUtilConstants_LINUX = [((NSString *) nil_chk(OrgApacheLuceneUtilConstants_OS_NAME)) java_hasPrefix:@"Linux"];
    OrgApacheLuceneUtilConstants_WINDOWS = [OrgApacheLuceneUtilConstants_OS_NAME java_hasPrefix:@"Windows"];
    OrgApacheLuceneUtilConstants_SUN_OS = [OrgApacheLuceneUtilConstants_OS_NAME java_hasPrefix:@"SunOS"];
    OrgApacheLuceneUtilConstants_MAC_OS_X = [OrgApacheLuceneUtilConstants_OS_NAME java_hasPrefix:@"Mac OS X"];
    JreStrongAssign(&OrgApacheLuceneUtilConstants_OS_ARCH, JavaLangSystem_getPropertyWithNSString_(@"os.arch"));
    JreStrongAssign(&OrgApacheLuceneUtilConstants_OS_VERSION, JavaLangSystem_getPropertyWithNSString_(@"os.version"));
    JreStrongAssign(&OrgApacheLuceneUtilConstants_JAVA_VENDOR, JavaLangSystem_getPropertyWithNSString_(@"java.vendor"));
    {
      NSString *x = JavaLangSystem_getPropertyWithNSString_(@"sun.arch.data.model");
      if (x != nil) {
        OrgApacheLuceneUtilConstants_JRE_IS_64BIT = ([x java_indexOfString:@"64"] != -1);
      }
      else {
        if (OrgApacheLuceneUtilConstants_OS_ARCH != nil && [OrgApacheLuceneUtilConstants_OS_ARCH java_indexOfString:@"64"] != -1) {
          OrgApacheLuceneUtilConstants_JRE_IS_64BIT = true;
        }
        else {
          OrgApacheLuceneUtilConstants_JRE_IS_64BIT = false;
        }
      }
      jboolean v6 = true;
      @try {
        [NSString_class_() getMethod:@"isEmpty" parameterTypes:[IOSObjectArray arrayWithLength:0 type:IOSClass_class_()]];
      }
      @catch (JavaLangNoSuchMethodException *nsme) {
        v6 = false;
      }
      OrgApacheLuceneUtilConstants_JRE_IS_MINIMUM_JAVA6 = v6;
      jboolean v7 = true;
      @try {
        [NSException_class_() getMethod:@"getSuppressed" parameterTypes:[IOSObjectArray arrayWithLength:0 type:IOSClass_class_()]];
      }
      @catch (JavaLangNoSuchMethodException *nsme) {
        v7 = false;
      }
      OrgApacheLuceneUtilConstants_JRE_IS_MINIMUM_JAVA7 = v7;
    }
    JreStrongAssign(&OrgApacheLuceneUtilConstants_LUCENE_MAIN_VERSION, OrgApacheLuceneUtilConstants_identWithNSString_(@"3.5"));
    {
      JavaLangPackage *pkg = OrgApacheLuceneLucenePackage_get();
      NSString *v = (pkg == nil) ? nil : [((JavaLangPackage *) nil_chk(pkg)) getImplementationVersion];
      if (v == nil) {
        v = JreStrcat("$$", OrgApacheLuceneUtilConstants_LUCENE_MAIN_VERSION, @"-SNAPSHOT");
      }
      else if (![v java_hasPrefix:OrgApacheLuceneUtilConstants_LUCENE_MAIN_VERSION]) {
        v = JreStrcat("$$$", OrgApacheLuceneUtilConstants_LUCENE_MAIN_VERSION, @"-SNAPSHOT ", v);
      }
      JreStrongAssign(&OrgApacheLuceneUtilConstants_LUCENE_VERSION, OrgApacheLuceneUtilConstants_identWithNSString_(v));
    }
    J2OBJC_SET_INITIALIZED(OrgApacheLuceneUtilConstants)
  }
}

@end

void OrgApacheLuceneUtilConstants_init(OrgApacheLuceneUtilConstants *self) {
  NSObject_init(self);
}

OrgApacheLuceneUtilConstants *new_OrgApacheLuceneUtilConstants_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneUtilConstants, init)
}

OrgApacheLuceneUtilConstants *create_OrgApacheLuceneUtilConstants_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneUtilConstants, init)
}

NSString *OrgApacheLuceneUtilConstants_identWithNSString_(NSString *s) {
  OrgApacheLuceneUtilConstants_initialize();
  return [((NSString *) nil_chk(s)) description];
}

IOSObjectArray *OrgApacheLuceneUtilConstants__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *OrgApacheLuceneUtilConstants__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *OrgApacheLuceneUtilConstants__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneUtilConstants)
