//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/search/payloads/PayloadTermQuery.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchPayloadsPayloadTermQuery")
#ifdef RESTRICT_OrgApacheLuceneSearchPayloadsPayloadTermQuery
#define INCLUDE_ALL_OrgApacheLuceneSearchPayloadsPayloadTermQuery 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchPayloadsPayloadTermQuery 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchPayloadsPayloadTermQuery

#if !defined (OrgApacheLuceneSearchPayloadsPayloadTermQuery_) && (INCLUDE_ALL_OrgApacheLuceneSearchPayloadsPayloadTermQuery || defined(INCLUDE_OrgApacheLuceneSearchPayloadsPayloadTermQuery))
#define OrgApacheLuceneSearchPayloadsPayloadTermQuery_

#define RESTRICT_OrgApacheLuceneSearchSpansSpanTermQuery 1
#define INCLUDE_OrgApacheLuceneSearchSpansSpanTermQuery 1
#include "org/apache/lucene/search/spans/SpanTermQuery.h"

@class OrgApacheLuceneIndexTerm;
@class OrgApacheLuceneSearchPayloadsPayloadFunction;
@class OrgApacheLuceneSearchSearcher;
@class OrgApacheLuceneSearchWeight;

@interface OrgApacheLuceneSearchPayloadsPayloadTermQuery : OrgApacheLuceneSearchSpansSpanTermQuery {
 @public
  OrgApacheLuceneSearchPayloadsPayloadFunction *function_;
}

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
withOrgApacheLuceneSearchPayloadsPayloadFunction:(OrgApacheLuceneSearchPayloadsPayloadFunction *)function;

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
withOrgApacheLuceneSearchPayloadsPayloadFunction:(OrgApacheLuceneSearchPayloadsPayloadFunction *)function
                                     withBoolean:(jboolean)includeSpanScore;

- (OrgApacheLuceneSearchWeight *)createWeightWithOrgApacheLuceneSearchSearcher:(OrgApacheLuceneSearchSearcher *)searcher;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchPayloadsPayloadTermQuery)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchPayloadsPayloadTermQuery, function_, OrgApacheLuceneSearchPayloadsPayloadFunction *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchPayloadsPayloadTermQuery_initWithOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchPayloadsPayloadFunction_(OrgApacheLuceneSearchPayloadsPayloadTermQuery *self, OrgApacheLuceneIndexTerm *term, OrgApacheLuceneSearchPayloadsPayloadFunction *function);

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery *new_OrgApacheLuceneSearchPayloadsPayloadTermQuery_initWithOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchPayloadsPayloadFunction_(OrgApacheLuceneIndexTerm *term, OrgApacheLuceneSearchPayloadsPayloadFunction *function) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery *create_OrgApacheLuceneSearchPayloadsPayloadTermQuery_initWithOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchPayloadsPayloadFunction_(OrgApacheLuceneIndexTerm *term, OrgApacheLuceneSearchPayloadsPayloadFunction *function);

FOUNDATION_EXPORT void OrgApacheLuceneSearchPayloadsPayloadTermQuery_initWithOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchPayloadsPayloadFunction_withBoolean_(OrgApacheLuceneSearchPayloadsPayloadTermQuery *self, OrgApacheLuceneIndexTerm *term, OrgApacheLuceneSearchPayloadsPayloadFunction *function, jboolean includeSpanScore);

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery *new_OrgApacheLuceneSearchPayloadsPayloadTermQuery_initWithOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchPayloadsPayloadFunction_withBoolean_(OrgApacheLuceneIndexTerm *term, OrgApacheLuceneSearchPayloadsPayloadFunction *function, jboolean includeSpanScore) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery *create_OrgApacheLuceneSearchPayloadsPayloadTermQuery_initWithOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchPayloadsPayloadFunction_withBoolean_(OrgApacheLuceneIndexTerm *term, OrgApacheLuceneSearchPayloadsPayloadFunction *function, jboolean includeSpanScore);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchPayloadsPayloadTermQuery)

#endif

#if !defined (OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_) && (INCLUDE_ALL_OrgApacheLuceneSearchPayloadsPayloadTermQuery || defined(INCLUDE_OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight))
#define OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_

#define RESTRICT_OrgApacheLuceneSearchSpansSpanWeight 1
#define INCLUDE_OrgApacheLuceneSearchSpansSpanWeight 1
#include "org/apache/lucene/search/spans/SpanWeight.h"

@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneSearchExplanation;
@class OrgApacheLuceneSearchPayloadsPayloadTermQuery;
@class OrgApacheLuceneSearchScorer;
@class OrgApacheLuceneSearchSearcher;

@interface OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight : OrgApacheLuceneSearchSpansSpanWeight

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery:(OrgApacheLuceneSearchPayloadsPayloadTermQuery *)outer$
                    withOrgApacheLuceneSearchPayloadsPayloadTermQuery:(OrgApacheLuceneSearchPayloadsPayloadTermQuery *)query
                                    withOrgApacheLuceneSearchSearcher:(OrgApacheLuceneSearchSearcher *)searcher;

- (OrgApacheLuceneSearchExplanation *)explainWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                                         withInt:(jint)doc;

- (OrgApacheLuceneSearchScorer *)scorerWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                               withBoolean:(jboolean)scoreDocsInOrder
                                                               withBoolean:(jboolean)topScorer;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight)

FOUNDATION_EXPORT void OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery_withOrgApacheLuceneSearchPayloadsPayloadTermQuery_withOrgApacheLuceneSearchSearcher_(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight *self, OrgApacheLuceneSearchPayloadsPayloadTermQuery *outer$, OrgApacheLuceneSearchPayloadsPayloadTermQuery *query, OrgApacheLuceneSearchSearcher *searcher);

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight *new_OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery_withOrgApacheLuceneSearchPayloadsPayloadTermQuery_withOrgApacheLuceneSearchSearcher_(OrgApacheLuceneSearchPayloadsPayloadTermQuery *outer$, OrgApacheLuceneSearchPayloadsPayloadTermQuery *query, OrgApacheLuceneSearchSearcher *searcher) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight *create_OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery_withOrgApacheLuceneSearchPayloadsPayloadTermQuery_withOrgApacheLuceneSearchSearcher_(OrgApacheLuceneSearchPayloadsPayloadTermQuery *outer$, OrgApacheLuceneSearchPayloadsPayloadTermQuery *query, OrgApacheLuceneSearchSearcher *searcher);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight)

#endif

#if !defined (OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer_) && (INCLUDE_ALL_OrgApacheLuceneSearchPayloadsPayloadTermQuery || defined(INCLUDE_OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer))
#define OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer_

#define RESTRICT_OrgApacheLuceneSearchSpansSpanScorer 1
#define INCLUDE_OrgApacheLuceneSearchSpansSpanScorer 1
#include "org/apache/lucene/search/spans/SpanScorer.h"

@class IOSByteArray;
@class OrgApacheLuceneSearchExplanation;
@class OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight;
@class OrgApacheLuceneSearchSimilarity;
@class OrgApacheLuceneSearchSpansTermSpans;
@class OrgApacheLuceneSearchWeight;
@protocol OrgApacheLuceneIndexTermPositions;

@interface OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer : OrgApacheLuceneSearchSpansSpanScorer {
 @public
  IOSByteArray *payload_;
  id<OrgApacheLuceneIndexTermPositions> positions_;
  jfloat payloadScore_;
  jint payloadsSeen_;
}

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight:(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight *)outer$
                                                withOrgApacheLuceneSearchSpansTermSpans:(OrgApacheLuceneSearchSpansTermSpans *)spans
                                                        withOrgApacheLuceneSearchWeight:(OrgApacheLuceneSearchWeight *)weight
                                                    withOrgApacheLuceneSearchSimilarity:(OrgApacheLuceneSearchSimilarity *)similarity
                                                                          withByteArray:(IOSByteArray *)norms;

- (jfloat)score;

#pragma mark Protected

- (OrgApacheLuceneSearchExplanation *)explainWithInt:(jint)doc;

- (jfloat)getPayloadScore;

- (jfloat)getSpanScore;

- (void)processPayloadWithOrgApacheLuceneSearchSimilarity:(OrgApacheLuceneSearchSimilarity *)similarity;

- (jboolean)setFreqCurrentDoc;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer, payload_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer, positions_, id<OrgApacheLuceneIndexTermPositions>)

FOUNDATION_EXPORT void OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_withOrgApacheLuceneSearchSpansTermSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer *self, OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight *outer$, OrgApacheLuceneSearchSpansTermSpans *spans, OrgApacheLuceneSearchWeight *weight, OrgApacheLuceneSearchSimilarity *similarity, IOSByteArray *norms);

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer *new_OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_withOrgApacheLuceneSearchSpansTermSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight *outer$, OrgApacheLuceneSearchSpansTermSpans *spans, OrgApacheLuceneSearchWeight *weight, OrgApacheLuceneSearchSimilarity *similarity, IOSByteArray *norms) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer *create_OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_withOrgApacheLuceneSearchSpansTermSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight *outer$, OrgApacheLuceneSearchSpansTermSpans *spans, OrgApacheLuceneSearchWeight *weight, OrgApacheLuceneSearchSimilarity *similarity, IOSByteArray *norms);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchPayloadsPayloadTermQuery_PayloadTermWeight_PayloadTermSpanScorer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchPayloadsPayloadTermQuery")
