//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/search/FilteredDocIdSetIterator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchFilteredDocIdSetIterator")
#ifdef RESTRICT_OrgApacheLuceneSearchFilteredDocIdSetIterator
#define INCLUDE_ALL_OrgApacheLuceneSearchFilteredDocIdSetIterator 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchFilteredDocIdSetIterator 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchFilteredDocIdSetIterator

#if !defined (OrgApacheLuceneSearchFilteredDocIdSetIterator_) && (INCLUDE_ALL_OrgApacheLuceneSearchFilteredDocIdSetIterator || defined(INCLUDE_OrgApacheLuceneSearchFilteredDocIdSetIterator))
#define OrgApacheLuceneSearchFilteredDocIdSetIterator_

#define RESTRICT_OrgApacheLuceneSearchDocIdSetIterator 1
#define INCLUDE_OrgApacheLuceneSearchDocIdSetIterator 1
#include "org/apache/lucene/search/DocIdSetIterator.h"

@interface OrgApacheLuceneSearchFilteredDocIdSetIterator : OrgApacheLuceneSearchDocIdSetIterator {
 @public
  OrgApacheLuceneSearchDocIdSetIterator *_innerIter_;
}

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneSearchDocIdSetIterator:(OrgApacheLuceneSearchDocIdSetIterator *)innerIter;

- (jint)advanceWithInt:(jint)target;

- (jint)docID;

- (jint)nextDoc;

#pragma mark Protected

- (jboolean)matchWithInt:(jint)doc;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchFilteredDocIdSetIterator)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFilteredDocIdSetIterator, _innerIter_, OrgApacheLuceneSearchDocIdSetIterator *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchFilteredDocIdSetIterator_initWithOrgApacheLuceneSearchDocIdSetIterator_(OrgApacheLuceneSearchFilteredDocIdSetIterator *self, OrgApacheLuceneSearchDocIdSetIterator *innerIter);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchFilteredDocIdSetIterator)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchFilteredDocIdSetIterator")
