//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/search/NRTManagerReopenThread.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchNRTManagerReopenThread")
#ifdef RESTRICT_OrgApacheLuceneSearchNRTManagerReopenThread
#define INCLUDE_ALL_OrgApacheLuceneSearchNRTManagerReopenThread 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchNRTManagerReopenThread 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchNRTManagerReopenThread

#if !defined (OrgApacheLuceneSearchNRTManagerReopenThread_) && (INCLUDE_ALL_OrgApacheLuceneSearchNRTManagerReopenThread || defined(INCLUDE_OrgApacheLuceneSearchNRTManagerReopenThread))
#define OrgApacheLuceneSearchNRTManagerReopenThread_

#define RESTRICT_JavaLangThread 1
#define INCLUDE_JavaLangThread 1
#include "java/lang/Thread.h"

#define RESTRICT_OrgApacheLuceneSearchNRTManager 1
#define INCLUDE_OrgApacheLuceneSearchNRTManager_WaitingListener 1
#include "org/apache/lucene/search/NRTManager.h"

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

@class OrgApacheLuceneSearchNRTManager;

@interface OrgApacheLuceneSearchNRTManagerReopenThread : JavaLangThread < OrgApacheLuceneSearchNRTManager_WaitingListener, JavaIoCloseable >

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneSearchNRTManager:(OrgApacheLuceneSearchNRTManager *)manager
                                             withDouble:(jdouble)targetMaxStaleSec
                                             withDouble:(jdouble)targetMinStaleSec;

- (void)close;

- (void)run;

- (void)waitingWithBoolean:(jboolean)needsDeletes
                  withLong:(jlong)targetGen;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchNRTManagerReopenThread)

FOUNDATION_EXPORT void OrgApacheLuceneSearchNRTManagerReopenThread_initWithOrgApacheLuceneSearchNRTManager_withDouble_withDouble_(OrgApacheLuceneSearchNRTManagerReopenThread *self, OrgApacheLuceneSearchNRTManager *manager, jdouble targetMaxStaleSec, jdouble targetMinStaleSec);

FOUNDATION_EXPORT OrgApacheLuceneSearchNRTManagerReopenThread *new_OrgApacheLuceneSearchNRTManagerReopenThread_initWithOrgApacheLuceneSearchNRTManager_withDouble_withDouble_(OrgApacheLuceneSearchNRTManager *manager, jdouble targetMaxStaleSec, jdouble targetMinStaleSec) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchNRTManagerReopenThread *create_OrgApacheLuceneSearchNRTManagerReopenThread_initWithOrgApacheLuceneSearchNRTManager_withDouble_withDouble_(OrgApacheLuceneSearchNRTManager *manager, jdouble targetMaxStaleSec, jdouble targetMinStaleSec);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchNRTManagerReopenThread)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchNRTManagerReopenThread")
