//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350.jar!org/apache/lucene/search/payloads/PayloadNearQuery.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/StringBuilder.h"
#include "java/util/Collection.h"
#include "java/util/Iterator.h"
#include "java/util/List.h"
#include "org/apache/lucene/index/IndexReader.h"
#include "org/apache/lucene/search/Explanation.h"
#include "org/apache/lucene/search/Scorer.h"
#include "org/apache/lucene/search/Searcher.h"
#include "org/apache/lucene/search/Similarity.h"
#include "org/apache/lucene/search/Weight.h"
#include "org/apache/lucene/search/payloads/AveragePayloadFunction.h"
#include "org/apache/lucene/search/payloads/PayloadFunction.h"
#include "org/apache/lucene/search/payloads/PayloadNearQuery.h"
#include "org/apache/lucene/search/spans/NearSpansOrdered.h"
#include "org/apache/lucene/search/spans/NearSpansUnordered.h"
#include "org/apache/lucene/search/spans/SpanNearQuery.h"
#include "org/apache/lucene/search/spans/SpanQuery.h"
#include "org/apache/lucene/search/spans/SpanScorer.h"
#include "org/apache/lucene/search/spans/SpanWeight.h"
#include "org/apache/lucene/search/spans/Spans.h"
#include "org/apache/lucene/util/ToStringUtils.h"

@interface OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight () {
 @public
  OrgApacheLuceneSearchPayloadsPayloadNearQuery *this$0_;
}

@end

@interface OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer () {
 @public
  OrgApacheLuceneSearchPayloadsPayloadNearQuery *this$0_;
  jint payloadsSeen_;
}

@end

@implementation OrgApacheLuceneSearchPayloadsPayloadNearQuery

- (instancetype)initWithOrgApacheLuceneSearchSpansSpanQueryArray:(IOSObjectArray *)clauses
                                                         withInt:(jint)slop
                                                     withBoolean:(jboolean)inOrder {
  OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_(self, clauses, slop, inOrder);
  return self;
}

- (instancetype)initWithOrgApacheLuceneSearchSpansSpanQueryArray:(IOSObjectArray *)clauses
                                                         withInt:(jint)slop
                                                     withBoolean:(jboolean)inOrder
                withOrgApacheLuceneSearchPayloadsPayloadFunction:(OrgApacheLuceneSearchPayloadsPayloadFunction *)function {
  OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_(self, clauses, slop, inOrder, function);
  return self;
}

- (OrgApacheLuceneSearchWeight *)createWeightWithOrgApacheLuceneSearchSearcher:(OrgApacheLuceneSearchSearcher *)searcher {
  return create_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_(self, self, searcher);
}

- (id)java_clone {
  jint sz = [((id<JavaUtilList>) nil_chk(clauses_)) size];
  IOSObjectArray *newClauses = [IOSObjectArray arrayWithLength:sz type:OrgApacheLuceneSearchSpansSpanQuery_class_()];
  for (jint i = 0; i < sz; i++) {
    IOSObjectArray_Set(newClauses, i, (OrgApacheLuceneSearchSpansSpanQuery *) cast_chk([((OrgApacheLuceneSearchSpansSpanQuery *) nil_chk([((id<JavaUtilList>) nil_chk(clauses_)) getWithInt:i])) java_clone], [OrgApacheLuceneSearchSpansSpanQuery class]));
  }
  OrgApacheLuceneSearchPayloadsPayloadNearQuery *boostingNearQuery = create_OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_(newClauses, slop_, inOrder_, function_);
  [boostingNearQuery setBoostWithFloat:[self getBoost]];
  return boostingNearQuery;
}

- (NSString *)toStringWithNSString:(NSString *)field {
  JavaLangStringBuilder *buffer = create_JavaLangStringBuilder_init();
  [buffer appendWithNSString:@"payloadNear(["];
  id<JavaUtilIterator> i = [((id<JavaUtilList>) nil_chk(clauses_)) iterator];
  while ([((id<JavaUtilIterator>) nil_chk(i)) hasNext]) {
    OrgApacheLuceneSearchSpansSpanQuery *clause = [i next];
    [buffer appendWithNSString:[((OrgApacheLuceneSearchSpansSpanQuery *) nil_chk(clause)) toStringWithNSString:field]];
    if ([i hasNext]) {
      [buffer appendWithNSString:@", "];
    }
  }
  [buffer appendWithNSString:@"], "];
  [buffer appendWithInt:slop_];
  [buffer appendWithNSString:@", "];
  [buffer appendWithBoolean:inOrder_];
  [buffer appendWithNSString:@")"];
  [buffer appendWithNSString:OrgApacheLuceneUtilToStringUtils_boostWithFloat_([self getBoost])];
  return [buffer description];
}

- (NSUInteger)hash {
  jint prime = 31;
  jint result = ((jint) [super hash]);
  result = prime * result + ((fieldName_ == nil) ? 0 : ((jint) [((NSString *) nil_chk(fieldName_)) hash]));
  result = prime * result + ((function_ == nil) ? 0 : ((jint) [((OrgApacheLuceneSearchPayloadsPayloadFunction *) nil_chk(function_)) hash]));
  return result;
}

- (jboolean)isEqual:(id)obj {
  if (self == obj) return true;
  if (![super isEqual:obj]) return false;
  if ([self java_getClass] != [nil_chk(obj) java_getClass]) return false;
  OrgApacheLuceneSearchPayloadsPayloadNearQuery *other = (OrgApacheLuceneSearchPayloadsPayloadNearQuery *) cast_chk(obj, [OrgApacheLuceneSearchPayloadsPayloadNearQuery class]);
  if (fieldName_ == nil) {
    if (other->fieldName_ != nil) return false;
  }
  else if (![fieldName_ isEqual:other->fieldName_]) return false;
  if (function_ == nil) {
    if (other->function_ != nil) return false;
  }
  else if (![function_ isEqual:other->function_]) return false;
  return true;
}

- (void)dealloc {
  RELEASE_(fieldName_);
  RELEASE_(function_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchWeight;", 0x1, 2, 3, 4, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 5, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 8, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 9, 10, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneSearchSpansSpanQueryArray:withInt:withBoolean:);
  methods[1].selector = @selector(initWithOrgApacheLuceneSearchSpansSpanQueryArray:withInt:withBoolean:withOrgApacheLuceneSearchPayloadsPayloadFunction:);
  methods[2].selector = @selector(createWeightWithOrgApacheLuceneSearchSearcher:);
  methods[3].selector = @selector(java_clone);
  methods[4].selector = @selector(toStringWithNSString:);
  methods[5].selector = @selector(hash);
  methods[6].selector = @selector(isEqual:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "fieldName_", "LNSString;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "function_", "LOrgApacheLuceneSearchPayloadsPayloadFunction;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "[LOrgApacheLuceneSearchSpansSpanQuery;IZ", "[LOrgApacheLuceneSearchSpansSpanQuery;IZLOrgApacheLuceneSearchPayloadsPayloadFunction;", "createWeight", "LOrgApacheLuceneSearchSearcher;", "LJavaIoIOException;", "clone", "toString", "LNSString;", "hashCode", "equals", "LNSObject;", "LOrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight;LOrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchPayloadsPayloadNearQuery = { "PayloadNearQuery", "org.apache.lucene.search.payloads", ptrTable, methods, fields, 7, 0x1, 7, 2, -1, 11, -1, -1, -1 };
  return &_OrgApacheLuceneSearchPayloadsPayloadNearQuery;
}

@end

void OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_(OrgApacheLuceneSearchPayloadsPayloadNearQuery *self, IOSObjectArray *clauses, jint slop, jboolean inOrder) {
  OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_(self, clauses, slop, inOrder, create_OrgApacheLuceneSearchPayloadsAveragePayloadFunction_init());
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery *new_OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_(IOSObjectArray *clauses, jint slop, jboolean inOrder) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery, initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_, clauses, slop, inOrder)
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery *create_OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_(IOSObjectArray *clauses, jint slop, jboolean inOrder) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery, initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_, clauses, slop, inOrder)
}

void OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_(OrgApacheLuceneSearchPayloadsPayloadNearQuery *self, IOSObjectArray *clauses, jint slop, jboolean inOrder, OrgApacheLuceneSearchPayloadsPayloadFunction *function) {
  OrgApacheLuceneSearchSpansSpanNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_(self, clauses, slop, inOrder);
  JreStrongAssign(&self->fieldName_, [((OrgApacheLuceneSearchSpansSpanQuery *) nil_chk(IOSObjectArray_Get(nil_chk(clauses), 0))) getField]);
  JreStrongAssign(&self->function_, function);
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery *new_OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_(IOSObjectArray *clauses, jint slop, jboolean inOrder, OrgApacheLuceneSearchPayloadsPayloadFunction *function) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery, initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_, clauses, slop, inOrder, function)
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery *create_OrgApacheLuceneSearchPayloadsPayloadNearQuery_initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_(IOSObjectArray *clauses, jint slop, jboolean inOrder, OrgApacheLuceneSearchPayloadsPayloadFunction *function) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery, initWithOrgApacheLuceneSearchSpansSpanQueryArray_withInt_withBoolean_withOrgApacheLuceneSearchPayloadsPayloadFunction_, clauses, slop, inOrder, function)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchPayloadsPayloadNearQuery)

@implementation OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight

- (instancetype)initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery:(OrgApacheLuceneSearchPayloadsPayloadNearQuery *)outer$
                              withOrgApacheLuceneSearchSpansSpanQuery:(OrgApacheLuceneSearchSpansSpanQuery *)query
                                    withOrgApacheLuceneSearchSearcher:(OrgApacheLuceneSearchSearcher *)searcher {
  OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_(self, outer$, query, searcher);
  return self;
}

- (OrgApacheLuceneSearchScorer *)scorerWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                               withBoolean:(jboolean)scoreDocsInOrder
                                                               withBoolean:(jboolean)topScorer {
  return create_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(this$0_, [((OrgApacheLuceneSearchSpansSpanQuery *) nil_chk(query_)) getSpansWithOrgApacheLuceneIndexIndexReader:reader], self, similarity_, [((OrgApacheLuceneIndexIndexReader *) nil_chk(reader)) normsWithNSString:[((OrgApacheLuceneSearchSpansSpanQuery *) nil_chk(query_)) getField]]);
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, 1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchScorer;", 0x1, 2, 3, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery:withOrgApacheLuceneSearchSpansSpanQuery:withOrgApacheLuceneSearchSearcher:);
  methods[1].selector = @selector(scorerWithOrgApacheLuceneIndexIndexReader:withBoolean:withBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LOrgApacheLuceneSearchPayloadsPayloadNearQuery;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneSearchSpansSpanQuery;LOrgApacheLuceneSearchSearcher;", "LJavaIoIOException;", "scorer", "LOrgApacheLuceneIndexIndexReader;ZZ", "LOrgApacheLuceneSearchPayloadsPayloadNearQuery;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight = { "PayloadNearSpanWeight", "org.apache.lucene.search.payloads", ptrTable, methods, fields, 7, 0x1, 2, 1, 4, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight;
}

@end

void OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight *self, OrgApacheLuceneSearchPayloadsPayloadNearQuery *outer$, OrgApacheLuceneSearchSpansSpanQuery *query, OrgApacheLuceneSearchSearcher *searcher) {
  JreStrongAssign(&self->this$0_, outer$);
  OrgApacheLuceneSearchSpansSpanWeight_initWithOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_(self, query, searcher);
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight *new_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_(OrgApacheLuceneSearchPayloadsPayloadNearQuery *outer$, OrgApacheLuceneSearchSpansSpanQuery *query, OrgApacheLuceneSearchSearcher *searcher) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight, initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_, outer$, query, searcher)
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight *create_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_(OrgApacheLuceneSearchPayloadsPayloadNearQuery *outer$, OrgApacheLuceneSearchSpansSpanQuery *query, OrgApacheLuceneSearchSearcher *searcher) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight, initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpanQuery_withOrgApacheLuceneSearchSearcher_, outer$, query, searcher)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanWeight)

@implementation OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer

- (instancetype)initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery:(OrgApacheLuceneSearchPayloadsPayloadNearQuery *)outer$
                                  withOrgApacheLuceneSearchSpansSpans:(OrgApacheLuceneSearchSpansSpans *)spans
                                      withOrgApacheLuceneSearchWeight:(OrgApacheLuceneSearchWeight *)weight
                                  withOrgApacheLuceneSearchSimilarity:(OrgApacheLuceneSearchSimilarity *)similarity
                                                        withByteArray:(IOSByteArray *)norms {
  OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(self, outer$, spans, weight, similarity, norms);
  return self;
}

- (void)getPayloadsWithOrgApacheLuceneSearchSpansSpansArray:(IOSObjectArray *)subSpans {
  for (jint i = 0; i < ((IOSObjectArray *) nil_chk(subSpans))->size_; i++) {
    if ([IOSObjectArray_Get(subSpans, i) isKindOfClass:[OrgApacheLuceneSearchSpansNearSpansOrdered class]]) {
      if ([((OrgApacheLuceneSearchSpansNearSpansOrdered *) nil_chk(((OrgApacheLuceneSearchSpansNearSpansOrdered *) cast_chk(IOSObjectArray_Get(subSpans, i), [OrgApacheLuceneSearchSpansNearSpansOrdered class])))) isPayloadAvailable]) {
        [self processPayloadsWithJavaUtilCollection:[((OrgApacheLuceneSearchSpansNearSpansOrdered *) nil_chk(((OrgApacheLuceneSearchSpansNearSpansOrdered *) cast_chk(IOSObjectArray_Get(subSpans, i), [OrgApacheLuceneSearchSpansNearSpansOrdered class])))) getPayload] withInt:[((OrgApacheLuceneSearchSpansSpans *) nil_chk(IOSObjectArray_Get(subSpans, i))) start] withInt:[((OrgApacheLuceneSearchSpansSpans *) nil_chk(IOSObjectArray_Get(subSpans, i))) end]];
      }
      [self getPayloadsWithOrgApacheLuceneSearchSpansSpansArray:[((OrgApacheLuceneSearchSpansNearSpansOrdered *) nil_chk(((OrgApacheLuceneSearchSpansNearSpansOrdered *) cast_chk(IOSObjectArray_Get(subSpans, i), [OrgApacheLuceneSearchSpansNearSpansOrdered class])))) getSubSpans]];
    }
    else if ([IOSObjectArray_Get(subSpans, i) isKindOfClass:[OrgApacheLuceneSearchSpansNearSpansUnordered class]]) {
      if ([((OrgApacheLuceneSearchSpansNearSpansUnordered *) nil_chk(((OrgApacheLuceneSearchSpansNearSpansUnordered *) cast_chk(IOSObjectArray_Get(subSpans, i), [OrgApacheLuceneSearchSpansNearSpansUnordered class])))) isPayloadAvailable]) {
        [self processPayloadsWithJavaUtilCollection:[((OrgApacheLuceneSearchSpansNearSpansUnordered *) nil_chk(((OrgApacheLuceneSearchSpansNearSpansUnordered *) cast_chk(IOSObjectArray_Get(subSpans, i), [OrgApacheLuceneSearchSpansNearSpansUnordered class])))) getPayload] withInt:[((OrgApacheLuceneSearchSpansSpans *) nil_chk(IOSObjectArray_Get(subSpans, i))) start] withInt:[((OrgApacheLuceneSearchSpansSpans *) nil_chk(IOSObjectArray_Get(subSpans, i))) end]];
      }
      [self getPayloadsWithOrgApacheLuceneSearchSpansSpansArray:[((OrgApacheLuceneSearchSpansNearSpansUnordered *) nil_chk(((OrgApacheLuceneSearchSpansNearSpansUnordered *) cast_chk(IOSObjectArray_Get(subSpans, i), [OrgApacheLuceneSearchSpansNearSpansUnordered class])))) getSubSpans]];
    }
  }
}

- (void)processPayloadsWithJavaUtilCollection:(id<JavaUtilCollection>)payLoads
                                      withInt:(jint)start
                                      withInt:(jint)end {
  for (IOSByteArray * __strong thePayload in nil_chk(payLoads)) {
    payloadScore_ = [((OrgApacheLuceneSearchPayloadsPayloadFunction *) nil_chk(this$0_->function_)) currentScoreWithInt:doc_ withNSString:this$0_->fieldName_ withInt:start withInt:end withInt:payloadsSeen_ withFloat:payloadScore_ withFloat:[((OrgApacheLuceneSearchSimilarity *) nil_chk(similarity_PayloadNearSpanScorer_)) scorePayloadWithInt:doc_ withNSString:this$0_->fieldName_ withInt:[((OrgApacheLuceneSearchSpansSpans *) nil_chk(spans_PayloadNearSpanScorer_)) start] withInt:[((OrgApacheLuceneSearchSpansSpans *) nil_chk(spans_PayloadNearSpanScorer_)) end] withByteArray:thePayload withInt:0 withInt:((IOSByteArray *) nil_chk(thePayload))->size_]];
    ++payloadsSeen_;
  }
}

- (jboolean)setFreqCurrentDoc {
  if (!more_) {
    return false;
  }
  doc_ = [((OrgApacheLuceneSearchSpansSpans *) nil_chk(spans_PayloadNearSpanScorer_)) doc];
  freq_ = 0.0f;
  payloadScore_ = 0;
  payloadsSeen_ = 0;
  do {
    jint matchLength = [((OrgApacheLuceneSearchSpansSpans *) nil_chk(spans_PayloadNearSpanScorer_)) end] - [((OrgApacheLuceneSearchSpansSpans *) nil_chk(spans_PayloadNearSpanScorer_)) start];
    JrePlusAssignFloatF(&freq_, [((OrgApacheLuceneSearchSimilarity *) nil_chk([self getSimilarity])) sloppyFreqWithInt:matchLength]);
    IOSObjectArray *spansArr = [IOSObjectArray arrayWithLength:1 type:OrgApacheLuceneSearchSpansSpans_class_()];
    IOSObjectArray_Set(spansArr, 0, spans_PayloadNearSpanScorer_);
    [self getPayloadsWithOrgApacheLuceneSearchSpansSpansArray:spansArr];
    more_ = [((OrgApacheLuceneSearchSpansSpans *) nil_chk(spans_PayloadNearSpanScorer_)) next];
  }
  while (more_ && (doc_ == [((OrgApacheLuceneSearchSpansSpans *) nil_chk(spans_PayloadNearSpanScorer_)) doc]));
  return true;
}

- (jfloat)score {
  return [super score] * [((OrgApacheLuceneSearchPayloadsPayloadFunction *) nil_chk(this$0_->function_)) docScoreWithInt:doc_ withNSString:this$0_->fieldName_ withInt:payloadsSeen_ withFloat:payloadScore_];
}

- (OrgApacheLuceneSearchExplanation *)explainWithInt:(jint)doc {
  OrgApacheLuceneSearchExplanation *result = create_OrgApacheLuceneSearchExplanation_init();
  OrgApacheLuceneSearchExplanation *nonPayloadExpl = [super explainWithInt:doc];
  [result addDetailWithOrgApacheLuceneSearchExplanation:nonPayloadExpl];
  OrgApacheLuceneSearchExplanation *payloadExpl = [((OrgApacheLuceneSearchPayloadsPayloadFunction *) nil_chk(this$0_->function_)) explainWithInt:doc withInt:payloadsSeen_ withFloat:payloadScore_];
  [result addDetailWithOrgApacheLuceneSearchExplanation:payloadExpl];
  [result setValueWithFloat:[((OrgApacheLuceneSearchExplanation *) nil_chk(nonPayloadExpl)) getValue] * [((OrgApacheLuceneSearchExplanation *) nil_chk(payloadExpl)) getValue]];
  [result setDescriptionWithNSString:@"PayloadNearQuery, product of:"];
  return result;
}

- (void)dealloc {
  RELEASE_(this$0_);
  RELEASE_(spans_PayloadNearSpanScorer_);
  RELEASE_(similarity_PayloadNearSpanScorer_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, 0, 1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, 1, -1, -1, -1 },
    { NULL, "V", 0x4, 4, 5, -1, 6, -1, -1 },
    { NULL, "Z", 0x4, -1, -1, 1, -1, -1, -1 },
    { NULL, "F", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchExplanation;", 0x4, 7, 8, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery:withOrgApacheLuceneSearchSpansSpans:withOrgApacheLuceneSearchWeight:withOrgApacheLuceneSearchSimilarity:withByteArray:);
  methods[1].selector = @selector(getPayloadsWithOrgApacheLuceneSearchSpansSpansArray:);
  methods[2].selector = @selector(processPayloadsWithJavaUtilCollection:withInt:withInt:);
  methods[3].selector = @selector(setFreqCurrentDoc);
  methods[4].selector = @selector(score);
  methods[5].selector = @selector(explainWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LOrgApacheLuceneSearchPayloadsPayloadNearQuery;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "spans_PayloadNearSpanScorer_", "LOrgApacheLuceneSearchSpansSpans;", .constantValue.asLong = 0, 0x0, 9, -1, -1, -1 },
    { "payloadScore_", "F", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "payloadsSeen_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "similarity_PayloadNearSpanScorer_", "LOrgApacheLuceneSearchSimilarity;", .constantValue.asLong = 0, 0x0, 10, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneSearchSpansSpans;LOrgApacheLuceneSearchWeight;LOrgApacheLuceneSearchSimilarity;[B", "LJavaIoIOException;", "getPayloads", "[LOrgApacheLuceneSearchSpansSpans;", "processPayloads", "LJavaUtilCollection;II", "(Ljava/util/Collection<[B>;II)V", "explain", "I", "spans", "similarity", "LOrgApacheLuceneSearchPayloadsPayloadNearQuery;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer = { "PayloadNearSpanScorer", "org.apache.lucene.search.payloads", ptrTable, methods, fields, 7, 0x1, 6, 5, 11, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer;
}

@end

void OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer *self, OrgApacheLuceneSearchPayloadsPayloadNearQuery *outer$, OrgApacheLuceneSearchSpansSpans *spans, OrgApacheLuceneSearchWeight *weight, OrgApacheLuceneSearchSimilarity *similarity, IOSByteArray *norms) {
  JreStrongAssign(&self->this$0_, outer$);
  OrgApacheLuceneSearchSpansSpanScorer_initWithOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(self, spans, weight, similarity, norms);
  JreStrongAssign(&self->similarity_PayloadNearSpanScorer_, [self getSimilarity]);
  JreStrongAssign(&self->spans_PayloadNearSpanScorer_, spans);
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer *new_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(OrgApacheLuceneSearchPayloadsPayloadNearQuery *outer$, OrgApacheLuceneSearchSpansSpans *spans, OrgApacheLuceneSearchWeight *weight, OrgApacheLuceneSearchSimilarity *similarity, IOSByteArray *norms) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer, initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_, outer$, spans, weight, similarity, norms)
}

OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer *create_OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer_initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_(OrgApacheLuceneSearchPayloadsPayloadNearQuery *outer$, OrgApacheLuceneSearchSpansSpans *spans, OrgApacheLuceneSearchWeight *weight, OrgApacheLuceneSearchSimilarity *similarity, IOSByteArray *norms) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer, initWithOrgApacheLuceneSearchPayloadsPayloadNearQuery_withOrgApacheLuceneSearchSpansSpans_withOrgApacheLuceneSearchWeight_withOrgApacheLuceneSearchSimilarity_withByteArray_, outer$, spans, weight, similarity, norms)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchPayloadsPayloadNearQuery_PayloadNearSpanScorer)
